# -*- coding: utf-8 -*-
ITEMS = [
{"cat":"okazje","slug":"zdjecia-miesieczne-dziecka","title":"Zdjęcia miesięczne dziecka — jak dokumentować pierwszy rok",
 "desc":"Zdjęcia miesięczne dziecka: jak co miesiąc uwiecznić rozwój maluszka, pomysły na spójną serię i prosty sposób na piękną pamiątkę.",
 "card":"Jak co miesiąc dokumentować rozwój maluszka i stworzyć spójną serię.",
 "lead":"Comiesięczne zdjęcia pokazują, jak błyskawicznie rośnie dziecko. Sekret udanej serii to spójność.",
 "secs":[
   {"h2":"Ten sam kadr co miesiąc","ps":["Fotografuj w tym samym miejscu, świetle i pozycji — dzięki temu zmiana z miesiąca na miesiąc robi największe wrażenie."]},
   {"h2":"Dodaj punkt odniesienia","ps":["Ta sama przytulanka albo karteczka z numerem miesiąca świetnie pokazuje skalę wzrostu."]},
   {"h2":"Stwórz spójną serię","ps":["Jednolita kolorystyka i styl sprawią, że 12 zdjęć ułoży się w piękną, kompletną opowieść."]},
   {"h2":"Złóż to w pamiątkę","ps":["Z serii miesięcznej zrobisz wyjątkowy kolaż albo fotoksiążkę. Profesjonalne kadry przygotujesz w BoboFoto."]},
 ]},
{"cat":"okazje","slug":"roczek-smash-cake-krok-po-kroku","title":"Smash cake na roczek — sesja krok po kroku",
 "desc":"Smash cake na roczek: jak przygotować sesję z tortem krok po kroku, co kupić, jak ustawić i jak uchwycić najlepsze emocje.",
 "card":"Sesja z tortem na pierwsze urodziny — przygotowanie, ustawienie, emocje.",
 "lead":"Smash cake to świetna zabawa: dziecko z radością rozgniata mały tort, a Ty łapiesz mnóstwo emocji.",
 "secs":[
   {"h2":"Przygotuj tort i miejsce","ps":["Mały, kolorowy tort i podłoga zabezpieczona folią lub kocem. Najlepsze jest jasne, gładkie tło."]},
   {"h2":"Wybierz dobrą porę","ps":["Zrób sesję, gdy maluch jest wyspany i najedzony (ale nie tuż po posiłku) — wtedy chętniej się bawi."]},
   {"h2":"Łap reakcje","ps":["Zdziwienie przy pierwszym dotknięciu, ubrudzona buzia, śmiech — to najlepsze kadry, rób serię."]},
   {"h2":"Dopracuj efekt","ps":["Najlepsze ujęcie z roczku przerobisz w BoboFoto na elegancki, urodzinowy portret."]},
 ]},
{"cat":"okazje","slug":"chrzest-co-zalozyc-dziecku","title":"Chrzest — co założyć dziecku do zdjęć",
 "desc":"Co założyć dziecku na chrzest do zdjęć? Tradycyjne i nowoczesne stylizacje, materiały i wskazówki na piękne, pamiątkowe kadry.",
 "card":"Tradycyjne i nowoczesne stylizacje chrzcielne — co dobrze wygląda na zdjęciach.",
 "lead":"Strój do chrztu to ważny element pamiątkowych zdjęć. Oto co sprawdza się najlepiej.",
 "secs":[
   {"h2":"Klasyczna biel","ps":["Biała szatka, sukienka lub pajacyk to ponadczasowy wybór, który pięknie wygląda na zdjęciach przez lata."]},
   {"h2":"Naturalne, miękkie materiały","ps":["Bawełna i delikatne tkaniny są wygodne dla dziecka i ładnie układają się w kadrze."]},
   {"h2":"Dodatki z umiarem","ps":["Czepek, haftowana szatka czy świeca chrzcielna jako detal — bez przeładowania."]},
   {"h2":"Pamiątkowy portret","ps":["Z domowego zdjęcia w chrzcielnej stylizacji stworzysz w BoboFoto elegancką pamiątkę."]},
 ]},
{"cat":"stylizacje","slug":"zdjecia-noworodka-w-stylu-boho","title":"Zdjęcia noworodka w stylu boho",
 "desc":"Zdjęcia noworodka w stylu boho: naturalne materiały, ciepłe odcienie, pióra i wianki. Inspiracje na przytulną, naturalną sesję.",
 "card":"Naturalne materiały, ciepłe odcienie i delikatne dodatki w klimacie boho.",
 "lead":"Styl boho to ciepło, naturalność i przytulność — świetnie pasuje do delikatności noworodka.",
 "secs":[
   {"h2":"Ziemista, ciepła paleta","ps":["Beże, brązy, terakota i kremy budują naturalny, boho klimat."]},
   {"h2":"Naturalne faktury","ps":["Dzianina, wiklina, makrama i lniane tkaniny dodają charakteru bez przepychu."]},
   {"h2":"Delikatne dodatki","ps":["Drobny wianek, suszone kwiaty czy piórko — subtelnie, by maluszek pozostał w centrum."]},
   {"h2":"Gotowy klimat boho","ps":["W BoboFoto wybierzesz boho tło i stylizację do domowego zdjęcia maluszka."]},
 ]},
{"cat":"stylizacje","slug":"naturalne-lifestyle-zdjecia-noworodka","title":"Naturalne, lifestyle’owe zdjęcia noworodka",
 "desc":"Lifestyle’owe zdjęcia noworodka: naturalne, nieupozowane kadry z codzienności — w łóżku, przy karmieniu, w ramionach rodziców.",
 "card":"Naturalne, nieupozowane kadry z codzienności rodziny z maluszkiem.",
 "lead":"Fotografia lifestyle łapie prawdziwe chwile, a nie sztywne pozy — to ona najlepiej oddaje klimat pierwszych dni.",
 "secs":[
   {"h2":"Łap codzienność","ps":["Karmienie, drzemka na piersi rodzica, leniwy poranek w pościeli — te chwile wzruszają najbardziej."]},
   {"h2":"Naturalne światło i wnętrze","ps":["Jasna sypialnia przy oknie to idealna, autentyczna sceneria. Nie potrzebujesz dekoracji."]},
   {"h2":"Mniej pozowania","ps":["Nie ustawiaj wszystkiego — pozwól chwili się wydarzyć i rób zdjęcia obok."]},
   {"h2":"Naturalny efekt","ps":["W BoboFoto delikatnie dopracujemy światło i kolor, zachowując autentyczność kadru."]},
 ]},
{"cat":"stylizacje","slug":"zdjecia-noworodka-z-tata","title":"Zdjęcia noworodka z tatą — pomysły na wzruszające kadry",
 "desc":"Zdjęcia noworodka z tatą: pomysły na czułe, męskie kadry — maluszek na ramieniu, dłoń taty, wspólny sen. Inspiracje i wskazówki.",
 "card":"Czułe, męskie kadry — maluszek na ramieniu taty, dłonie, wspólny sen.",
 "lead":"Zdjęcia z tatą mają wyjątkowy, wzruszający charakter — kontrast siły i kruchości działa za każdym razem.",
 "secs":[
   {"h2":"Maluszek na przedramieniu","ps":["Noworodek wtulony w ramię taty to klasyczny, pełen czułości i bezpieczny kadr."]},
   {"h2":"Kontrast dłoni","ps":["Wielka dłoń taty obejmująca maleńką stópkę pięknie pokazuje skalę i więź."]},
   {"h2":"Prostota","ps":["Stonowany, gładki podkoszulek taty i spokojne tło — uwaga skupia się na emocji."]},
   {"h2":"Dopracowana oprawa","ps":["W BoboFoto nadamy wspólnemu zdjęciu profesjonalny, studyjny charakter."]},
 ]},
{"cat":"praktyka","slug":"jak-ubrac-noworodka-zima-do-zdjec","title":"Jak ubrać noworodka zimą do zdjęć",
 "desc":"Jak ubrać noworodka zimą do zdjęć, by było mu ciepło i wyglądał uroczo? Materiały, warstwy i pomysły na zimowe stylizacje.",
 "card":"Ciepło i uroczo — materiały, warstwy i pomysły na zimowe stylizacje.",
 "lead":"Zimą najważniejsze, by maluszkowi było ciepło — a przy okazji może wyglądać przeuroczo.",
 "secs":[
   {"h2":"Ciepłe, miękkie dzianiny","ps":["Wełniane i bawełniane czapeczki z uszkami, otulacze i pajacyki dają ciepło i zimowy klimat."]},
   {"h2":"Warstwy zamiast grubości","ps":["Kilka cienkich warstw lepiej grzeje i ładniej wygląda niż jedna gruba — łatwo też regulować temperaturę."]},
   {"h2":"Ciepły pokój","ps":["Do zdjęć w domu podkręć temperaturę — zadowolony, ogrzany maluszek pozuje spokojniej."]},
   {"h2":"Zimowa stylizacja online","ps":["W BoboFoto dobierzesz przytulne, zimowe tło do domowego zdjęcia."]},
 ]},
{"cat":"praktyka","slug":"odcisk-stopki-i-dloni-noworodka","title":"Odcisk stópki i dłoni noworodka — jak zrobić pamiątkę",
 "desc":"Jak zrobić odcisk stópki i dłoni noworodka? Bezpieczne metody (tusz, masa, glinka) i pomysły na połączenie z pamiątkowym zdjęciem.",
 "card":"Bezpieczne metody odcisku (tusz, masa) i połączenie ze zdjęciem maluszka.",
 "lead":"Odcisk maleńkiej stópki to trójwymiarowa pamiątka, która wzrusza po latach. Oto jak go bezpiecznie zrobić.",
 "secs":[
   {"h2":"Wybierz bezpieczną metodę","ps":["Zestawy z bezpiecznym tuszem lub masą zapewniają wyraźny odcisk bez ryzyka dla skóry maluszka."]},
   {"h2":"Działaj, gdy dziecko śpi","ps":["Rozluźniona, śpiąca rączka i stópka dają najwyraźniejszy odcisk."]},
   {"h2":"Połącz ze zdjęciem","ps":["Odcisk obok pamiątkowego portretu maluszka tworzy piękną kompozycję na ścianę."]},
   {"h2":"Oprawa zdjęcia","ps":["Profesjonalny portret do takiej pamiątki przygotujesz w BoboFoto."]},
 ]},
{"cat":"okazje","slug":"pierwsze-zdjecie-po-porodzie","title":"Pierwsze zdjęcie po porodzie — jak je uchwycić",
 "desc":"Pierwsze zdjęcie po porodzie: jak uwiecznić te wyjątkowe, pierwsze chwile z maluszkiem w szpitalu i w domu.",
 "card":"Jak uchwycić wyjątkowe pierwsze chwile z maluszkiem tuż po narodzinach.",
 "lead":"Pierwsze chwile po porodzie są niepowtarzalne. Nawet proste zdjęcie telefonem stanie się bezcenną pamiątką.",
 "secs":[
   {"h2":"Łap emocje, nie perfekcję","ps":["Zmęczenie i wzruszenie mamy, maleńki maluszek na klatce piersiowej — autentyczność jest tu najważniejsza."]},
   {"h2":"Detale pierwszych chwil","ps":["Opaska identyfikacyjna, pierwszy czepek, dłoń trzymająca rączkę — uchwyć te drobiazgi."]},
   {"h2":"Naturalne światło","ps":["Przy oknie zdjęcia wyjdą cieplej niż w świetle szpitalnych jarzeniówek."]},
   {"h2":"Pamiątka na lata","ps":["Nawet zwykłe zdjęcie z sali możemy w BoboFoto delikatnie dopracować, zachowując jego naturalność."]},
 ]},
{"cat":"okazje","slug":"kartka-swiateczna-ze-zdjeciem-dziecka","title":"Kartka świąteczna ze zdjęciem dziecka — jak zrobić",
 "desc":"Jak zrobić kartkę świąteczną ze zdjęciem dziecka? Pomysły na kadr, format i tekst oraz jak przygotować ją szybko i ładnie.",
 "card":"Pomysły na kadr, format i tekst — świąteczna kartka z maluszkiem.",
 "lead":"Kartka świąteczna ze zdjęciem maluszka to najmilsza forma życzeń dla rodziny. Oto jak ją przygotować.",
 "secs":[
   {"h2":"Świąteczny, ale czytelny kadr","ps":["Stonowane świąteczne tło i miejsce na życzenia sprawią, że kartka będzie elegancka, a nie przeładowana."]},
   {"h2":"Dobierz format","ps":["Pionowy układ pasuje na klasyczną kartkę, kwadrat — do wysłania w social mediach."]},
   {"h2":"Krótki, ciepły tekst","ps":["Imię dziecka i proste życzenia w stonowanym foncie wystarczą."]},
   {"h2":"Gotowa w jeden dzień","ps":["W BoboFoto przygotujesz świąteczny kadr z domowego zdjęcia w ~10 godzin."]},
 ]},
{"cat":"praktyka","slug":"co-zrobic-ze-zdjeciami-noworodka","title":"Co zrobić ze zdjęciami noworodka — pomysły",
 "desc":"Co zrobić ze zdjęciami noworodka? Pomysły: fotoksiążka, obraz na ścianę, kartki, kubek, kalendarz. Jak wykorzystać piękne kadry.",
 "card":"Fotoksiążka, obraz na ścianę, kartki, kubek — pomysły na wykorzystanie zdjęć.",
 "lead":"Piękne zdjęcia maluszka aż proszą się o coś więcej niż folder w telefonie. Oto pomysły, jak je wykorzystać.",
 "secs":[
   {"h2":"Fotoksiążka","ps":["Najpiękniejsza forma — pierwsze tygodnie zamknięte w jednej, trwałej pamiątce."]},
   {"h2":"Obraz lub plakat na ścianę","ps":["Duży, elegancki portret maluszka pięknie ożywia pokój dziecięcy lub salon."]},
   {"h2":"Drobne upominki","ps":["Kubek, magnes, kartka czy kalendarz ze zdjęciem to świetny prezent dla dziadków."]},
   {"h2":"Zacznij od dobrych kadrów","ps":["Im lepsze zdjęcia, tym piękniejsze pamiątki. Profesjonalne wersje stworzysz w BoboFoto."]},
 ]},
{"cat":"stylizacje","slug":"zdjecia-noworodka-z-balonami","title":"Zdjęcia noworodka z balonami — pomysły na pierwszy miesiąc",
 "desc":"Zdjęcia noworodka z balonami: pomysły na uczczenie pierwszego miesiąca lub miesięcznicy. Kolory, ustawienie i bezpieczeństwo.",
 "card":"Pomysły na uczczenie pierwszego miesiąca — kolory, ustawienie, bezpieczeństwo.",
 "lead":"Balony to prosty sposób, by świętować pierwszy miesiąc maluszka i dodać zdjęciom radosnego akcentu.",
 "secs":[
   {"h2":"Stonowane kolory","ps":["Pastelowe lub jednokolorowe balony wyglądają elegancko i nie przytłaczają kadru."]},
   {"h2":"Balon z liczbą","ps":["Balon w kształcie cyfry (np. „1 miesiąc”) to czytelny i uroczy motyw."]},
   {"h2":"Bezpieczeństwo","ps":["Trzymaj balony z dala od buzi dziecka i zawsze pod kontrolą dorosłego."]},
   {"h2":"Dopracowany kadr","ps":["W BoboFoto połączysz domowe zdjęcie z czystym, świątecznym tłem."]},
 ]},
{"cat":"stylizacje","slug":"zdjecia-noworodka-do-ramki-i-na-sciane","title":"Zdjęcia noworodka do ramki i na ścianę",
 "desc":"Jak wybrać zdjęcie noworodka do ramki lub na ścianę? Format, kadr i stylistyka, które najlepiej wyglądają w domowej galerii.",
 "card":"Format, kadr i styl, które najlepiej wyglądają na ścianie i w ramce.",
 "lead":"Zdjęcie na ścianę towarzyszy rodzinie codziennie — warto wybrać takie, które nie znudzi się przez lata.",
 "secs":[
   {"h2":"Stawiaj na ponadczasowość","ps":["Klasyczne, stonowane kadry pasują do każdego wnętrza i nie wychodzą z mody."]},
   {"h2":"Pomyśl o formacie","ps":["Portret pionowy świetnie wygląda w ramce, kadr poziomy — nad łóżeczkiem czy kanapą."]},
   {"h2":"Spójność z wnętrzem","ps":["Dobierz kolorystykę zdjęcia do palety pokoju — całość będzie wyglądać jak zaplanowana."]},
   {"h2":"Jakość do druku","ps":["Do dużego wydruku potrzebujesz dobrego pliku — przygotujemy go w BoboFoto."]},
 ]},
{"cat":"technika","slug":"jak-zrobic-piekne-tlo-w-domu","title":"Jak zrobić piękne tło do zdjęć w domu",
 "desc":"Jak przygotować piękne, proste tło do zdjęć noworodka w domu? Tanie sposoby na gładkie, jednolite tło bez profesjonalnego sprzętu.",
 "card":"Tanie sposoby na gładkie, jednolite tło bez profesjonalnego sprzętu.",
 "lead":"Nie potrzebujesz studyjnego tła — w domu masz wszystko, by zrobić czyste, profesjonalnie wyglądające ujęcia.",
 "secs":[
   {"h2":"Gładki koc lub prześcieradło","ps":["Jednolity, stonowany materiał rozłożony bez zagnieceń to najprostsze i najlepsze tło."]},
   {"h2":"Łóżko przy oknie","ps":["Białą pościel przy oknie wykorzystasz jako jasne, naturalne tło zalane miękkim światłem."]},
   {"h2":"Usuń to, co rozprasza","ps":["Schowaj kable, zabawki i bałagan z kadru — czyste tło to połowa sukcesu."]},
   {"h2":"Resztę dołożymy my","ps":["Jeśli chcesz prawdziwie studyjne tło, w BoboFoto wymienimy je na profesjonalne."]},
 ]},
{"cat":"praktyka","slug":"zdjecia-noworodka-bez-ubranka-bezpiecznie","title":"Zdjęcia noworodka bez ubranka — jak zrobić bezpiecznie",
 "desc":"Zdjęcia noworodka bez ubranka: jak zadbać o ciepło, bezpieczeństwo i komfort maluszka oraz uzyskać delikatne, naturalne kadry.",
 "card":"Jak zadbać o ciepło i bezpieczeństwo i uzyskać delikatne, naturalne kadry.",
 "lead":"Delikatne kadry otulonego lub nagiego maluszka są piękne — pod warunkiem, że zadbasz o jego komfort i ciepło.",
 "secs":[
   {"h2":"Ciepło to podstawa","ps":["Mocno dogrzej pokój. Wychłodzony noworodek będzie płakał — ciepło to klucz do spokojnej sesji."]},
   {"h2":"Miękkie, bezpieczne podłoże","ps":["Gruby koc i asekuracja dorosłego przez cały czas. Nigdy nie zostawiaj dziecka bez opieki."]},
   {"h2":"Delikatne otulenie","ps":["Lekko otulony maluszek czuje się bezpiecznie i ładnie wygląda — to bezpieczniejsza alternatywa."]},
   {"h2":"Naturalny efekt","ps":["W BoboFoto dopracujemy światło i tło, zachowując delikatność i naturalność kadru."]},
 ]},
{"cat":"poradnik","slug":"pomysly-na-podpis-pod-zdjeciem-noworodka","title":"Pomysły na podpis pod zdjęciem noworodka",
 "desc":"Pomysły na podpis pod zdjęciem noworodka na Instagram i Facebook: ciepłe, krótkie i wzruszające teksty oraz cytaty o dziecku.",
 "card":"Ciepłe, krótkie teksty i cytaty pod zdjęcie maluszka w social mediach.",
 "lead":"Dobry podpis dodaje zdjęciu emocji. Oto pomysły na ciepłe, proste teksty pod kadry maluszka.",
 "secs":[
   {"h2":"Krótko i z serca","ps":["Najlepiej działają proste zdania: powitanie maluszka, data, imię, jedno szczere zdanie o emocjach."]},
   {"h2":"Metryczka w podpisie","ps":["Imię, data, waga i wzrost to klasyk, który sprawdza się przy ogłoszeniu narodzin."]},
   {"h2":"Dodaj odrobinę humoru","ps":["Lekki, ciepły żart o nieprzespanych nocach świetnie rozluźnia i angażuje znajomych."]},
   {"h2":"Najpierw piękne zdjęcie","ps":["Podpis wzmacnia kadr, ale to zdjęcie robi pierwsze wrażenie — zadbaj o nie z BoboFoto."]},
 ]},
]
