# -*- coding: utf-8 -*-
ITEMS = [
{
 "cat": "stylizacje",
 "slug": "pomysly-na-stylizacje-zdjec-noworodka",
 "title": "Pomysły na stylizacje zdjęć noworodka",
 "desc": "Pomysły i inspiracje na stylizacje zdjęć noworodka: klasyka studyjna, motywy świąteczne, pory roku i eleganckie tła premium.",
 "card": "Klasyka, święta i pory roku — inspiracje na tła i stylizacje, które najlepiej wyglądają.",
 "lead": "Wybór tła i stylizacji potrafi całkowicie zmienić charakter zdjęcia noworodka. Oto sprawdzone pomysły na piękne kadry.",
 "secs": [
   {"h2": "Klasyka, która nigdy się nie nudzi", "ps": ["Stonowane tła w beżach, bieli i szałwiowej zieleni sprawiają, że cała uwaga skupia się na dziecku. To wybór ponadczasowy."]},
   {"h2": "Motywy świąteczne i sezonowe", "ps": ["Mały elf, zimowa kraina, wielkanocne pastele czy jesienne dynie tworzą wzruszające, okolicznościowe pamiątki."]},
   {"h2": "Elegancja premium", "ps": ["Szmaragd i złoto, granatowy aksamit czy stylizacje vintage dają efekt „jak z okładki” dla wyjątkowych kadrów."]},
   {"h2": "Jak wybrać stylizację", "ps": ["Dopasuj kolory do karnacji dziecka, postaw na stonowane odcienie i nie bój się zamówić kilku wersji. W <strong>BoboFoto.pl</strong> masz do wyboru ponad 30 teł."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "kolory-tla-do-zdjec-noworodka",
 "title": "Kolory tła do zdjęć noworodka — co pasuje najlepiej",
 "desc": "Jakie kolory tła pasują do zdjęć noworodka? Beż, biel, szałwia, pudrowy róż — przewodnik po barwach, które podkreślają delikatną skórę maluszka.",
 "card": "Przewodnik po kolorach tła, które podkreślają delikatną skórę maluszka.",
 "lead": "Kolor tła wpływa na nastrój zdjęcia i na to, jak wygląda skóra dziecka. Oto barwy, które sprawdzają się najlepiej.",
 "secs": [
   {"h2": "Neutralne beże i biele", "ps": ["Najbezpieczniejszy wybór — pasują do każdej karnacji i wnętrza, wyglądają czysto i ponadczasowo."]},
   {"h2": "Szałwiowa zieleń i pudrowy róż", "ps": ["Delikatne, stonowane kolory dodają charakteru, nie odciągając uwagi od maluszka."]},
   {"h2": "Głębokie barwy dla efektu premium", "ps": ["Granat, butelkowa zieleń czy grafit świetnie kontrastują z jasną skórą i dają elegancki, studyjny efekt."]},
   {"h2": "Czego unikać", "ps": ["Jaskrawych, nasyconych kolorów (np. mocna czerwień, neon) — potrafią dawać refleksy na skórze i przytłaczać kadr."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "rekwizyty-do-sesji-noworodkowej",
 "title": "Rekwizyty do sesji noworodkowej — co się sprawdza",
 "desc": "Jakie rekwizyty wykorzystać na sesji noworodkowej? Kosze, kocyki, opaski i pamiątki rodzinne — pomysły i zasada umiaru.",
 "card": "Kosze, kocyki, opaski i pamiątki — co dodać do kadru i kiedy mniej znaczy więcej.",
 "lead": "Dobre rekwizyty podkreślają maluszka, a nie kradną mu show. Oto te, które sprawdzają się najlepiej.",
 "secs": [
   {"h2": "Miękkie kocyki i otulacze", "ps": ["Dzianinowe kocyki i otulacze dodają przytulności i pomagają ułożyć dziecko w schludny, bezpieczny sposób."]},
   {"h2": "Kosze i drewniane łóżeczka", "ps": ["Naturalne, neutralne rekwizyty tworzą przytulną scenę — pamiętaj o asekuracji i miękkim wyściełaniu."]},
   {"h2": "Delikatne opaski i czapeczki", "ps": ["Subtelny dodatek na głowie ociepla kadr; wybieraj miękkie, nieuciskające materiały."]},
   {"h2": "Zasada umiaru", "ps": ["Jeden–dwa rekwizyty w stonowanych barwach wystarczą. Zbyt wiele dodatków odwraca uwagę od najważniejszego — dziecka."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "ubranka-do-sesji-noworodkowej",
 "title": "W co ubrać noworodka na sesję zdjęciową",
 "desc": "W co ubrać noworodka na sesję? Najlepsze materiały, kolory i fasony ubranek do zdjęć maluszka oraz czego unikać.",
 "card": "Najlepsze materiały, kolory i fasony ubranek do zdjęć — plus czego unikać.",
 "lead": "Strój maluszka powinien być przede wszystkim wygodny i prosty. Oto jak dobrać ubranko, by zdjęcia wyglądały pięknie.",
 "secs": [
   {"h2": "Stawiaj na naturalne materiały", "ps": ["Bawełna, len i miękka dzianina są przewiewne, delikatne dla skóry i ładnie układają się na zdjęciu."]},
   {"h2": "Stonowane, jednolite kolory", "ps": ["Biel, beż, kremowy i pastele wyglądają czysto i nie rywalizują z buzią dziecka."]},
   {"h2": "Wygoda ponad wszystko", "ps": ["Unikaj ciasnych gumek i metek, które uwierają — zestresowany maluszek nie pozwoli zrobić spokojnych zdjęć."]},
   {"h2": "Albo bez ubranka", "ps": ["Delikatnie otulony kocykiem noworodek to klasyczny, ponadczasowy kadr — wystarczy ciepły pokój i miękkie podłoże."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-noworodka-z-rodzicami",
 "title": "Zdjęcia noworodka z rodzicami — pomysły na wspólne kadry",
 "desc": "Pomysły na zdjęcia noworodka z rodzicami: naturalne, czułe kadry z mamą i tatą, które warto uwiecznić w pierwszych tygodniach.",
 "card": "Naturalne, czułe kadry maluszka z mamą i tatą — pomysły na wspólne zdjęcia.",
 "lead": "Zdjęcia z rodzicami to jedne z najcenniejszych pamiątek — pokazują więź i skalę maleństwa w kochających dłoniach.",
 "secs": [
   {"h2": "Maluszek na piersi rodzica", "ps": ["Śpiące dziecko na klatce mamy lub taty to bezpieczny, wzruszający i bardzo naturalny kadr."]},
   {"h2": "Dłonie i skala", "ps": ["Maleńka rączka w dłoni rodzica pięknie oddaje, jak malutkie jest dziecko."]},
   {"h2": "Postaw na prostotę", "ps": ["Jednolite, jasne ubrania rodziców i spokojne tło sprawią, że uwaga skupi się na emocjach, nie na strojach."]},
   {"h2": "Wspólny portret bez wychodzenia z domu", "ps": ["W BoboFoto.pl z domowego zdjęcia stworzysz elegancki, wspólny kadr w pięknej stylizacji."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-noworodka-z-rodzenstwem",
 "title": "Zdjęcia noworodka z rodzeństwem — jak je zrobić",
 "desc": "Jak zrobić udane zdjęcia noworodka ze starszym rodzeństwem? Bezpieczeństwo, pomysły na pozy i sposób na naturalne kadry.",
 "card": "Bezpieczne pozy i triki na naturalne kadry maluszka ze starszym rodzeństwem.",
 "lead": "Zdjęcie noworodka ze starszym bratem lub siostrą to piękna pamiątka początku rodzeństwa — wymaga jednak odrobiny sprytu.",
 "secs": [
   {"h2": "Bezpieczeństwo przede wszystkim", "ps": ["Starsze dziecko niech siedzi oparte, a noworodka ułóż na jego kolanach z asekuracją dorosłego tuż obok kadru."]},
   {"h2": "Łap naturalne emocje", "ps": ["Buziak w czółko, wspólne przytulanie — najlepsze kadry powstają, gdy starszak jest zrelaksowany, a nie „ustawiany”."]},
   {"h2": "Działaj szybko", "ps": ["Cierpliwość małych dzieci jest krótka — przygotuj scenę wcześniej i rób dużo zdjęć w krótkim czasie."]},
   {"h2": "Spójna stylizacja", "ps": ["Ubierz dzieci w zbliżone, stonowane kolory. W BoboFoto.pl dopasujesz tło, by wspólny kadr wyglądał profesjonalnie."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "minimalistyczna-sesja-noworodkowa",
 "title": "Minimalistyczna sesja noworodkowa — piękno prostoty",
 "desc": "Minimalistyczna sesja noworodkowa: jak mniej znaczy więcej. Stonowane tła, naturalne światło i ponadczasowe, czyste kadry maluszka.",
 "card": "Mniej znaczy więcej — stonowane tła i czyste, ponadczasowe kadry.",
 "lead": "Minimalizm w fotografii noworodkowej nigdy nie wychodzi z mody. Czyste kadry skupiają uwagę tam, gdzie trzeba — na dziecku.",
 "secs": [
   {"h2": "Jedno tło, jeden nastrój", "ps": ["Gładkie, neutralne tło i brak zbędnych dodatków dają elegancki, ponadczasowy efekt."]},
   {"h2": "Naturalne światło", "ps": ["Miękkie światło z okna to cała „dekoracja”, jakiej potrzebujesz w minimalistycznym kadrze."]},
   {"h2": "Detale zamiast dodatków", "ps": ["Zamiast rekwizytów postaw na detale ciała: rzęsy, dłonie, usta. To one budują emocje."]},
   {"h2": "Czysty, studyjny efekt", "ps": ["W BoboFoto.pl stworzysz minimalistyczny portret z domowego zdjęcia — bez bałaganu, z profesjonalnym światłem."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-noworodka-w-kosze-i-otulaczu",
 "title": "Zdjęcia noworodka w koszu i otulaczu — przytulne kadry",
 "desc": "Jak zrobić przytulne zdjęcia noworodka w koszyku lub otulaczu? Bezpieczne ułożenie, miękkie wyściełanie i pomysły na kadry.",
 "card": "Przytulne kadry w koszyku i otulaczu — bezpieczne ułożenie i pomysły.",
 "lead": "Kosz wyłożony miękkim kocykiem albo delikatne otulenie dają poczucie bezpieczeństwa i tworzą urocze, przytulne zdjęcia.",
 "secs": [
   {"h2": "Miękkie, bezpieczne wyściełanie", "ps": ["Wyłóż kosz grubym kocem i zwiniętymi ręcznikami, by maluszek leżał stabilnie i wygodnie."]},
   {"h2": "Otulenie dla spokoju", "ps": ["Lekko otulony noworodek czuje się jak w brzuszku — częściej śpi spokojnie i ładnie wygląda na zdjęciu."]},
   {"h2": "Asekuracja w każdej chwili", "ps": ["Przy zdjęciach w koszu zawsze trzymaj rękę w pobliżu dziecka — bezpieczeństwo jest ważniejsze niż kadr."]},
   {"h2": "Dopracuj tło", "ps": ["Neutralne tło wokół kosza wzmacnia przytulny klimat. W BoboFoto.pl dobierzesz pasujące, profesjonalne tło online."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-noworodka-z-misiem-i-przytulanka",
 "title": "Zdjęcia noworodka z misiem i przytulanką",
 "desc": "Zdjęcia noworodka z ulubioną przytulanką lub misiem: jak pokazać skalę maluszka i stworzyć wzruszającą pamiątkę.",
 "card": "Miś i przytulanka jako element kadru — skala maluszka i wzruszająca pamiątka.",
 "lead": "Ulubiona przytulanka obok maluszka to nie tylko urocza dekoracja — to też sposób, by za lata pamiętać, jak mały był na początku.",
 "secs": [
   {"h2": "Miś pokazuje skalę", "ps": ["Pluszak ułożony obok dziecka świetnie oddaje jego maleńki rozmiar — szczególnie, gdy powtórzysz kadr po roku."]},
   {"h2": "Wybierz stonowaną przytulankę", "ps": ["Miś w neutralnym kolorze pasuje do każdej stylizacji i nie odciąga uwagi od maluszka."]},
   {"h2": "Naturalne ułożenie", "ps": ["Połóż przytulankę tak, jakby „spała” obok dziecka — wygląda to naturalnie i wzruszająco."]},
   {"h2": "Tradycja na lata", "ps": ["Rób takie zdjęcie co roku z tym samym misiem. W BoboFoto.pl przygotujesz spójną, ładną oprawę każdego kadru."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-noworodka-z-pieskiem",
 "title": "Zdjęcia noworodka z pieskiem — jak zrobić bezpiecznie",
 "desc": "Jak bezpiecznie zrobić zdjęcia noworodka z psem? Zasady bezpieczeństwa, spokój zwierzaka i pomysły na wspólne, urocze kadry.",
 "card": "Bezpieczne, urocze kadry maluszka z domowym pupilem — zasady i pomysły.",
 "lead": "Pies to często pełnoprawny członek rodziny. Wspólne zdjęcie z noworodkiem jest urocze — pod warunkiem zachowania zasad bezpieczeństwa.",
 "secs": [
   {"h2": "Bezpieczeństwo to podstawa", "ps": ["Nigdy nie zostawiaj psa sam na sam z noworodkiem. Dorosły powinien kontrolować zwierzaka przez cały czas."]},
   {"h2": "Wybierz spokojny moment", "ps": ["Zmęczony, najedzony i wyspacerowany pies będzie spokojniejszy i łatwiej uchwycisz zgrany kadr."]},
   {"h2": "Łap krótkie chwile", "ps": ["Pies nie pozuje długo — przygotuj scenę i rób serie zdjęć, by złapać ten jeden idealny moment."]},
   {"h2": "Dopracuj efekt", "ps": ["Spokojne tło wyróżni dwójkę bohaterów. W BoboFoto.pl poprawisz oprawę wspólnego zdjęcia, zachowując naturalność."]},
 ],
},
]
