# -*- coding: utf-8 -*-
ITEMS = [
{
 "cat": "praktyka",
 "slug": "sesja-noworodkowa-krok-po-kroku",
 "title": "Sesja noworodkowa krok po kroku — jak się przygotować",
 "desc": "Sesja noworodkowa krok po kroku: od przygotowania maluszka i pokoju, przez zdjęcie, po odbiór gotowych kadrów. Prosty przewodnik dla rodziców.",
 "card": "Cały przebieg sesji od A do Z — przygotowanie, zdjęcie, odbiór gotowych kadrów.",
 "lead": "Pierwsza sesja bywa stresująca, ale wcale nie musi. Oto cały przebieg krok po kroku — tak, żebyś wiedziała dokładnie, czego się spodziewać.",
 "secs": [
   {"h2": "Krok 1: wybierz spokojną porę", "ps": ["Najedzony i wyspany maluszek to podstawa. Zaplanuj sesję na porę, gdy dziecko zwykle jest pogodne (często przedpołudnie)."]},
   {"h2": "Krok 2: przygotuj scenę", "ps": ["Ciepły pokój, gładki koc przy oknie, usunięty bałagan z tła. Miej pod ręką chusteczki i zapasowe ubranko."]},
   {"h2": "Krok 3: zrób zdjęcie", "ps": ["Wystarczy jedno dobre ujęcie z telefonu w naturalnym świetle. Rób serię — z kilkudziesięciu kadrów wybierzesz najlepszy."]},
   {"h2": "Krok 4: wyślij i odbierz efekt", "ps": ["W <strong>BoboFoto</strong> przesyłasz zdjęcie, wybierasz tło i pakiet, płacisz online, a gotową sesję odbierasz zwykle w ~10 godzin."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-blizniat-jak-zrobic",
 "title": "Zdjęcia bliźniąt — jak zrobić piękne kadry dwójki maluszków",
 "desc": "Jak zrobić udane zdjęcia bliźniąt? Bezpieczne ułożenie dwójki noworodków, pomysły na wspólne kadry i wskazówki dla rodziców bliźniaków.",
 "card": "Bezpieczne ułożenie i pomysły na wspólne kadry dwójki maluszków.",
 "lead": "Zdjęcia bliźniąt to podwójna radość i podwójne wyzwanie. Z kilkoma trikami uchwycisz piękne wspólne kadry.",
 "secs": [
   {"h2": "Ułóż maluszki blisko siebie", "ps": ["Najpiękniejsze są kadry, gdy bliźnięta się stykają — główka przy główce lub rączka na rączce. Asekuruj obie pociechy."]},
   {"h2": "Działaj, gdy oboje śpią", "ps": ["Najłatwiej złapać spokojny kadr, gdy obie pociechy są najedzone i senne w tym samym czasie."]},
   {"h2": "Spójna stylizacja", "ps": ["Identyczne lub komplementarne otulacze podkreślają, że to bliźnięta, i ładnie komponują kadr."]},
   {"h2": "Dopracuj efekt", "ps": ["W BoboFoto dobierzesz wspólne tło i stylizację dla obojga, zachowując ich naturalny wygląd."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "zdjecia-wczesniaka",
 "title": "Zdjęcia wcześniaka — jak je robić delikatnie i bezpiecznie",
 "desc": "Zdjęcia wcześniaka: jak fotografować najmniejszych maluszków z troską o bezpieczeństwo i komfort. Delikatne pomysły na pamiątkowe kadry.",
 "card": "Jak z troską uwiecznić najmniejszych maluszków — bezpiecznie i delikatnie.",
 "lead": "Wcześniaki są wyjątkowo delikatne, a ich pierwsze zdjęcia bywają tym cenniejsze. Najważniejsze to spokój i bezpieczeństwo.",
 "secs": [
   {"h2": "Bezpieczeństwo ponad wszystko", "ps": ["Jeśli maluszek jest pod opieką medyczną, zawsze stosuj się do zaleceń personelu. Rób zdjęcia spokojnie, bez przemęczania dziecka."]},
   {"h2": "Łap detale i skalę", "ps": ["Maleńka dłoń w palcach rodzica wyjątkowo wzruszająco oddaje, jak malutki jest wcześniak."]},
   {"h2": "Delikatne, ciepłe światło", "ps": ["Miękkie światło z okna i ciepły pokój to komfort dla dziecka i piękny efekt na zdjęciu."]},
   {"h2": "Pamiątka na lata", "ps": ["Nawet zwykłe zdjęcie z domu czy szpitala możemy w BoboFoto przekształcić w delikatny, pamiątkowy portret."]},
 ],
},
{
 "cat": "okazje",
 "slug": "pierwsza-kapiel-dziecka-zdjecia",
 "title": "Pierwsza kąpiel dziecka — jak uwiecznić ten moment",
 "desc": "Pierwsza kąpiel noworodka to wzruszający moment. Jak zrobić bezpieczne i urocze zdjęcia podczas kąpieli maluszka — praktyczne wskazówki.",
 "card": "Jak bezpiecznie i uroczo uchwycić wzruszający moment pierwszej kąpieli.",
 "lead": "Pierwsza kąpiel to mnóstwo emocji — i świetna okazja na naturalne, pełne czułości zdjęcia.",
 "secs": [
   {"h2": "Bezpieczeństwo przede wszystkim", "ps": ["Jedna osoba zawsze trzyma dziecko, druga robi zdjęcia. Nigdy nie zostawiaj maluszka samego przy wodzie."]},
   {"h2": "Łap emocje, nie pozy", "ps": ["Mina zdziwienia, rączki w wodzie, ręcznik z kapturkiem po kąpieli — to najbardziej urocze kadry."]},
   {"h2": "Uważaj na światło i parę", "ps": ["W łazience bywa ciemno i parno — przetrzyj obiektyw i wpuść jak najwięcej światła."]},
   {"h2": "Zrób z tego pamiątkę", "ps": ["Najlepszy kadr po kąpieli (maluszek w ręczniku) świetnie nadaje się na profesjonalny portret w BoboFoto."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-rodzinne-z-noworodkiem",
 "title": "Zdjęcia rodzinne z noworodkiem — pomysły na wspólne kadry",
 "desc": "Zdjęcia rodzinne z noworodkiem: jak ustawić całą rodzinę, co założyć i jak uzyskać naturalne, ciepłe kadry z maluszkiem.",
 "card": "Jak ustawić całą rodzinę i uzyskać naturalne, ciepłe kadry z maluszkiem.",
 "lead": "Pierwsze wspólne zdjęcie całej rodziny z nowym członkiem to pamiątka bezcenna. Oto jak je dobrze zrobić.",
 "secs": [
   {"h2": "Maluszek w centrum", "ps": ["Ustawcie się blisko siebie, z dzieckiem pośrodku lub na rękach rodzica — bliskość buduje ciepło kadru."]},
   {"h2": "Spójne, stonowane stroje", "ps": ["Wybierzcie 2–3 wspólne kolory bez mocnych wzorów — wtedy uwaga skupia się na Was, nie na ubraniach."]},
   {"h2": "Naturalność zamiast sztywnych póz", "ps": ["Najlepsze kadry powstają w ruchu: przytulenie, buziak, spojrzenie na dziecko."]},
   {"h2": "Profesjonalna oprawa", "ps": ["W BoboFoto dopasujemy tło i światło do wspólnego zdjęcia, by wyglądało jak z rodzinnej sesji studyjnej."]},
 ],
},
{
 "cat": "okazje",
 "slug": "ogloszenie-narodzin-dziecka-zdjecie",
 "title": "Ogłoszenie narodzin dziecka — pomysły na zdjęcie",
 "desc": "Jak zrobić zdjęcie do ogłoszenia narodzin dziecka? Pomysły na kadr z imieniem, wagą i datą oraz gotowe inspiracje do social mediów.",
 "card": "Pomysły na kadr z imieniem, wagą i datą — idealny do ogłoszenia narodzin.",
 "lead": "Ogłoszenie narodzin to pierwsza wielka nowina dla rodziny i znajomych. Dobre zdjęcie sprawi, że zapadnie w pamięć.",
 "secs": [
   {"h2": "Dodaj metryczkę", "ps": ["Imię, data urodzenia, waga i wzrost obok maluszka tworzą czytelne, urocze ogłoszenie."]},
   {"h2": "Prosty, czysty kadr", "ps": ["Stonowane tło i delikatne dodatki sprawią, że tekst i dziecko będą dobrze widoczne."]},
   {"h2": "Dopasuj format", "ps": ["Kwadrat sprawdzi się na Instagramie i Facebooku, format pionowy — na kartkę lub wydruk."]},
   {"h2": "Gotowe w jeden dzień", "ps": ["W BoboFoto przygotujesz elegancki kadr z miejscem na metryczkę z domowego zdjęcia."]},
 ],
},
{
 "cat": "technika",
 "slug": "telefon-czy-aparat-do-zdjec-noworodka",
 "title": "Telefon czy aparat do zdjęć noworodka — co wybrać",
 "desc": "Telefon czy aparat do zdjęć noworodka? Porównanie możliwości, kiedy wystarczy smartfon i jak wycisnąć z niego maksimum jakości.",
 "card": "Kiedy wystarczy smartfon, a kiedy aparat — i jak wycisnąć maksimum jakości.",
 "lead": "Nie musisz kupować drogiego aparatu, żeby mieć piękne zdjęcia maluszka. W większości przypadków wystarczy telefon.",
 "secs": [
   {"h2": "Współczesny telefon w zupełności wystarczy", "ps": ["Aparaty w smartfonach robią zdjęcia w jakości, która spokojnie nadaje się na wydruk i social media — pod warunkiem dobrego światła."]},
   {"h2": "Kiedy aparat ma przewagę", "ps": ["Lustrzanka/bezlusterkowiec daje lepsze rozmycie tła i więcej swobody przy słabym świetle — ale wymaga umiejętności."]},
   {"h2": "Klucz to światło, nie sprzęt", "ps": ["Nawet najlepszy aparat nie pomoże w ciemnym pokoju. Dobre światło z okna ma większe znaczenie niż cena sprzętu."]},
   {"h2": "Resztę dopracujemy my", "ps": ["Wyślij zdjęcie z telefonu do BoboFoto — profesjonalne tło, światło i stylizację dołożymy za Ciebie."]},
 ],
},
{
 "cat": "technika",
 "slug": "jak-poprawic-jakosc-zdjec-z-telefonu",
 "title": "Jak poprawić jakość zdjęć z telefonu",
 "desc": "Jak poprawić jakość zdjęć z telefonu? Czyszczenie obiektywu, światło, ostrość i ustawienia, które od razu podniosą poziom Twoich kadrów.",
 "card": "Proste triki, które od razu podnoszą jakość zdjęć robionych telefonem.",
 "lead": "Kilka drobiazgów potrafi zamienić przeciętne zdjęcie z telefonu w naprawdę dobre. Oto najważniejsze.",
 "secs": [
   {"h2": "Wyczyść obiektyw", "ps": ["Brzmi banalnie, ale zatłuszczony obiektyw to najczęstszy powód mglistych zdjęć. Przetrzyj go przed każdą serią."]},
   {"h2": "Dodaj światła", "ps": ["Podejdź do okna. Więcej światła = krótszy czas naświetlania = ostrzejsze, czystsze zdjęcia bez szumu."]},
   {"h2": "Ustaw ostrość i ekspozycję", "ps": ["Dotknij ekranu na twarzy dziecka — telefon ustawi tam ostrość i jasność."]},
   {"h2": "Nie używaj cyfrowego zoomu", "ps": ["Zoom w telefonie psuje jakość. Zamiast przybliżać, po prostu podejdź bliżej."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-noworodka-na-instagram",
 "title": "Zdjęcia noworodka na Instagram — jak ładnie pokazać maluszka",
 "desc": "Jak zrobić zdjęcia noworodka pod Instagram? Format, spójny styl, kadrowanie i pomysły na estetyczny feed z maluszkiem.",
 "card": "Format, spójny styl i pomysły na estetyczny feed z maluszkiem.",
 "lead": "Chcesz dzielić się zdjęciami maluszka w pięknym stylu? Kilka zasad sprawi, że Twój feed będzie spójny i estetyczny.",
 "secs": [
   {"h2": "Postaw na spójną kolorystykę", "ps": ["Trzymaj się jednej palety (np. ciepłe beże) — feed wygląda wtedy profesjonalnie i przyjemnie."]},
   {"h2": "Format kwadrat lub 4:5", "ps": ["Kwadrat i format pionowy 4:5 zajmują najwięcej miejsca w aplikacji i najlepiej się prezentują."]},
   {"h2": "Mniej znaczy więcej", "ps": ["Czyste tła i jeden bohater kadru (maluszek) działają lepiej niż przeładowane sceny."]},
   {"h2": "Gotowe, estetyczne kadry", "ps": ["W BoboFoto dostaniesz spójne stylistycznie zdjęcia, które od razu pasują na Instagram."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "jak-wybrac-najlepsze-zdjecie-noworodka",
 "title": "Jak wybrać najlepsze zdjęcie noworodka z sesji",
 "desc": "Jak wybrać najlepsze zdjęcie noworodka spośród wielu kadrów? Na co zwracać uwagę: ostrość, światło, emocje i kadr.",
 "card": "Na co patrzeć przy wyborze: ostrość, światło, emocje i kadr.",
 "lead": "Gdy masz dziesiątki podobnych zdjęć, wybór bywa trudny. Oto prosta lista, która pomoże wskazać te najlepsze.",
 "secs": [
   {"h2": "Sprawdź ostrość oczu", "ps": ["Najpierw odrzuć kadry, w których oczy (lub twarz) są nieostre — to one przyciągają wzrok."]},
   {"h2": "Szukaj emocji", "ps": ["Delikatny uśmiech, ziewnięcie, spokojny sen — kadr z emocją wygrywa z idealnym, ale „pustym”."]},
   {"h2": "Oceń światło i tło", "ps": ["Wybierz zdjęcia z miękkim światłem i czystym tłem — łatwiej je potem dopracować."]},
   {"h2": "Postaw na różnorodność", "ps": ["Do albumu wybierz różne typy: portret, detale, ujęcie z rodzicem — całość będzie ciekawsza."]},
 ],
},
{
 "cat": "stylizacje",
 "slug": "zdjecia-noworodka-z-metryczka",
 "title": "Zdjęcia noworodka z metryczką (imię, waga, data)",
 "desc": "Zdjęcia noworodka z metryczką: jak ładnie połączyć kadr maluszka z imieniem, datą urodzenia, wagą i wzrostem. Pomysły na pamiątkę.",
 "card": "Jak ładnie połączyć kadr maluszka z imieniem, datą, wagą i wzrostem.",
 "lead": "Metryczka na zdjęciu to urocza pamiątka i gotowe ogłoszenie narodzin w jednym. Oto jak ją dobrze skomponować.",
 "secs": [
   {"h2": "Co umieścić na metryczce", "ps": ["Najczęściej: imię, data i godzina urodzenia, waga i wzrost. Czasem też dzień tygodnia lub znak zodiaku."]},
   {"h2": "Czytelna, elegancka typografia", "ps": ["Delikatny, prosty font w stonowanym kolorze wygląda najlepiej i nie odciąga uwagi od dziecka."]},
   {"h2": "Zostaw miejsce w kadrze", "ps": ["Przy robieniu zdjęcia zostaw trochę pustej przestrzeni obok maluszka — tam wpadnie tekst."]},
   {"h2": "Gotowy projekt", "ps": ["W BoboFoto przygotujemy elegancki kadr z metryczką z Twojego domowego zdjęcia."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "prezent-na-baby-shower-pomysly",
 "title": "Prezent na baby shower — pomysły, które zachwycą",
 "desc": "Pomysły na prezent na baby shower: praktyczne, pamiątkowe i oryginalne — w tym voucher na sesję noworodkową online.",
 "card": "Praktyczne, pamiątkowe i oryginalne pomysły — w tym voucher na sesję.",
 "lead": "Szukasz prezentu na baby shower, który naprawdę ucieszy przyszłych rodziców? Oto sprawdzone pomysły.",
 "secs": [
   {"h2": "Praktyczne", "ps": ["Kosz wyprawkowy, kocyki, otulacze, kosmetyki dla maluszka — zawsze się przydają."]},
   {"h2": "Pamiątkowe", "ps": ["Pierwsza pościel, ramka na zdjęcie, pudełko na pierwsze pamiątki czy odcisk stópki po narodzinach."]},
   {"h2": "Oryginalne", "ps": ["Voucher na profesjonalną sesję noworodkową to prezent, który zostaje na lata — i nie zajmuje miejsca w szafie."]},
   {"h2": "Voucher BoboFoto", "ps": ["Sesja online od 9,90 zł to niedrogi, a wzruszający pomysł — rodzice sami wybiorą stylizację po narodzinach."]},
 ],
},
{
 "cat": "miasta",
 "slug": "sesja-noworodkowa-online-warszawa",
 "title": "Sesja noworodkowa online — Warszawa",
 "desc": "Sesja noworodkowa online dla rodziców z Warszawy. Bez dojazdu przez korki, bez wożenia noworodka do studia — profesjonalne zdjęcia od 9,90 zł.",
 "card": "Dla rodziców z Warszawy — bez korków i dojazdu, profesjonalne zdjęcia od 9,90 zł.",
 "lead": "Mieszkasz w Warszawie i nie chcesz wozić noworodka przez korki do studia? Sesja online BoboFoto powstaje u Ciebie w domu.",
 "secs": [
   {"h2": "Bez dojazdu przez całą Warszawę", "ps": ["Z Białołęki, Mokotowa, Ursynowa czy Pragi — nie tracisz godziny w korkach z maluszkiem. Robisz zdjęcie w domu, my robimy resztę."]},
   {"h2": "Jak to działa", "ps": ["Wysyłasz jedno zdjęcie z telefonu, wybierasz tło, płacisz online (BLIK/karta), a gotowe kadry odbierasz zwykle w ~10 godzin."]},
   {"h2": "Cena", "ps": ["Od 9,90 zł (Mini), 29 zł (Standard), 49 zł (Premium) — znacznie taniej niż tradycyjna sesja w warszawskim studiu (400–600 zł)."]},
   {"h2": "Dla kogo", "ps": ["Dla zabieganych warszawskich rodziców, którzy chcą piękną pamiątkę bez stresu i dojazdów."]},
 ],
},
{
 "cat": "miasta",
 "slug": "sesja-noworodkowa-online-krakow",
 "title": "Sesja noworodkowa online — Kraków",
 "desc": "Sesja noworodkowa online dla rodziców z Krakowa. Profesjonalne zdjęcia maluszka bez wychodzenia z domu, gotowe w ~10 h, od 9,90 zł.",
 "card": "Dla rodziców z Krakowa — profesjonalne zdjęcia bez wychodzenia z domu.",
 "lead": "W Krakowie nie musisz szukać terminu w studiu ani jechać przez miasto z noworodkiem — sesję zrobisz online, z domu.",
 "secs": [
   {"h2": "Wygoda dla krakowskich rodziców", "ps": ["Z Nowej Huty, Podgórza, Krowodrzy czy spod Wawelu — wszystko załatwiasz z kanapy, bez dojazdu i czekania na termin."]},
   {"h2": "Jak to działa", "ps": ["Jedno zdjęcie z telefonu, wybór tła, płatność online — gotowa sesja w ~10 godzin."]},
   {"h2": "Cena", "ps": ["Od 9,90 zł, bez ukrytych kosztów — taniej niż klasyczna sesja w krakowskim studiu."]},
   {"h2": "Dla kogo", "ps": ["Dla rodziców z Krakowa i okolic, którzy cenią czas i chcą ładną pamiątkę bez stresu."]},
 ],
},
{
 "cat": "miasta",
 "slug": "sesja-noworodkowa-online-wroclaw",
 "title": "Sesja noworodkowa online — Wrocław",
 "desc": "Sesja noworodkowa online dla rodziców z Wrocławia. Wyślij zdjęcie z domu, wybierz tło i odbierz profesjonalne kadry od 9,90 zł.",
 "card": "Dla rodziców z Wrocławia — wyślij zdjęcie z domu, odbierz gotowe kadry.",
 "lead": "Rodzice z Wrocławia coraz częściej wybierają sesję online — bez dojazdu, bez stresu i taniej niż w studiu.",
 "secs": [
   {"h2": "Cały Wrocław bez wychodzenia z domu", "ps": ["Z Krzyków, Psiego Pola, Fabrycznej czy ze Starego Miasta — sesję zrobisz zdalnie, kiedy maluszek jest spokojny."]},
   {"h2": "Jak to działa", "ps": ["Przesyłasz jedno zdjęcie, wybierasz stylizację, płacisz online, a efekt odbierasz w ~10 godzin."]},
   {"h2": "Cena", "ps": ["Pakiety od 9,90 do 49 zł — ułamek ceny tradycyjnej sesji noworodkowej."]},
   {"h2": "Dla kogo", "ps": ["Dla wrocławskich rodziców szukających wygodnej i niedrogiej pamiątki z pierwszych dni dziecka."]},
 ],
},
{
 "cat": "miasta",
 "slug": "sesja-noworodkowa-online-poznan",
 "title": "Sesja noworodkowa online — Poznań",
 "desc": "Sesja noworodkowa online dla rodziców z Poznania. Profesjonalne zdjęcia noworodka bez dojazdu, gotowe w ~10 godzin, już od 9,90 zł.",
 "card": "Dla rodziców z Poznania — profesjonalne zdjęcia bez dojazdu, od 9,90 zł.",
 "lead": "W Poznaniu zrobisz sesję noworodkową bez wychodzenia z domu — wystarczy telefon i kilka minut.",
 "secs": [
   {"h2": "Wygoda w całym Poznaniu", "ps": ["Z Jeżyc, Wildy, Grunwaldu czy Naramowic — bez dojazdu i wożenia maluszka po mieście."]},
   {"h2": "Jak to działa", "ps": ["Jedno zdjęcie z domu, wybór tła, płatność online i gotowe kadry w ~10 godzin."]},
   {"h2": "Cena", "ps": ["Od 9,90 zł — bez ukrytych kosztów, znacznie taniej niż sesja w poznańskim studiu."]},
   {"h2": "Dla kogo", "ps": ["Dla poznańskich rodziców, którzy chcą piękną pamiątkę szybko i wygodnie."]},
 ],
},
{
 "cat": "miasta",
 "slug": "sesja-noworodkowa-online-trojmiasto",
 "title": "Sesja noworodkowa online — Trójmiasto (Gdańsk, Gdynia, Sopot)",
 "desc": "Sesja noworodkowa online dla rodziców z Trójmiasta — Gdańsk, Gdynia, Sopot. Zdjęcia maluszka bez dojazdu, od 9,90 zł, gotowe w ~10 h.",
 "card": "Dla rodziców z Gdańska, Gdyni i Sopotu — sesja bez dojazdu, od 9,90 zł.",
 "lead": "Gdańsk, Gdynia, Sopot — gdziekolwiek w Trójmieście jesteś, sesję noworodkową zrobisz online, prosto z domu.",
 "secs": [
   {"h2": "Całe Trójmiasto bez dojazdu", "ps": ["Bez jeżdżenia między Gdańskiem, Gdynią a Sopotem z noworodkiem — wszystko robisz zdalnie."]},
   {"h2": "Jak to działa", "ps": ["Wysyłasz zdjęcie, wybierasz tło, płacisz online, a profesjonalne kadry odbierasz w ~10 godzin."]},
   {"h2": "Cena", "ps": ["Od 9,90 zł — taniej i wygodniej niż tradycyjna sesja w trójmiejskim studiu."]},
   {"h2": "Dla kogo", "ps": ["Dla rodziców z Trójmiasta i okolic, którzy cenią wygodę i piękną pamiątkę."]},
 ],
},
{
 "cat": "miasta",
 "slug": "sesja-noworodkowa-online-slask",
 "title": "Sesja noworodkowa online — Śląsk (Katowice i okolice)",
 "desc": "Sesja noworodkowa online dla rodziców ze Śląska — Katowice, Gliwice, Zabrze i okolice. Zdjęcia maluszka bez dojazdu, od 9,90 zł.",
 "card": "Dla rodziców ze Śląska — Katowice, Gliwice, Zabrze i okolice, bez dojazdu.",
 "lead": "Na Śląsku, w gęstej aglomeracji, sesja online to wygoda nie do przecenienia — bez dojazdów między miastami z maluszkiem.",
 "secs": [
   {"h2": "Cała aglomeracja online", "ps": ["Z Katowic, Gliwic, Zabrza, Sosnowca czy Chorzowa — zamiast jeździć po regionie, robisz zdjęcie w domu."]},
   {"h2": "Jak to działa", "ps": ["Przesyłasz jedno zdjęcie, wybierasz stylizację, płacisz online, a efekt masz w ~10 godzin."]},
   {"h2": "Cena", "ps": ["Pakiety od 9,90 zł — bez ukrytych kosztów, taniej niż klasyczne studio na Śląsku."]},
   {"h2": "Dla kogo", "ps": ["Dla śląskich rodziców szukających szybkiej, wygodnej i niedrogiej pamiątki."]},
 ],
},
]
