# -*- coding: utf-8 -*-
ITEMS = [
{
 "cat": "technika",
 "slug": "jak-zrobic-zdjecia-noworodka-w-domu",
 "title": "Jak zrobić piękne zdjęcia noworodka w domu — 7 wskazówek",
 "desc": "Jak zrobić piękne zdjęcia noworodka w domu telefonem? 7 praktycznych wskazówek: światło, pora dnia, kadr, tło i bezpieczeństwo maluszka.",
 "card": "7 prostych wskazówek, dzięki którym zdjęcie z telefonu wyjdzie naprawdę dobrze — światło, kadr, pora dnia i bezpieczeństwo.",
 "lead": "Nie potrzebujesz drogiego sprzętu ani studia, żeby uwiecznić pierwsze dni maluszka. Wystarczy telefon, odrobina światła i kilka prostych zasad.",
 "secs": [
   {"h2": "Wybierz dobrą porę dnia", "ps": ["Najlepsze zdjęcia powstają przy <strong>miękkim, naturalnym świetle</strong> — zwykle rano lub wczesnym popołudniem. Unikaj ostrego słońca w południe i żółtego światła żarówek wieczorem."]},
   {"h2": "Ustaw maluszka blisko okna", "ps": ["Światło z okna to Twój najlepszy „softbox”. Ułóż dziecko tak, aby światło padało <strong>z boku</strong> — to nadaje zdjęciu głębi. Mocne słońce złagodź cienką firanką."]},
   {"h2": "Postaw na proste, jasne tło", "ps": ["Gładki koc lub prześcieradło w stonowanym kolorze (beż, biel, szałwiowa zieleń) sprawią, że uwaga skupi się na dziecku. Usuń z kadru zabawki, kable i bałagan."]},
   {"h2": "Łap detale i rób dużo ujęć", "ps": ["Maleńkie dłonie, stópki, rzęsy, dłoń rodzica trzymająca rączkę — to kadry, które wzruszają najbardziej. Rób serie zdjęć; z kilkudziesięciu zawsze znajdzie się to jedno wyjątkowe."]},
   {"h2": "Resztę zostaw profesjonalistom", "ps": ["Nawet zwykłe domowe zdjęcie można zamienić w kadr jak ze studia. W <strong>BoboFoto.pl</strong> wysyłasz jedno zdjęcie, wybierasz tło, a gotową sesję odbierasz w ~10 godzin. Twarz i rysy dziecka pozostają bez zmian."]},
 ],
},
{
 "cat": "technika",
 "slug": "najlepsze-swiatlo-do-zdjec-noworodka",
 "title": "Najlepsze światło do zdjęć noworodka — jak je ustawić",
 "desc": "Jakie światło jest najlepsze do zdjęć noworodka? Naturalne światło z okna, pora dnia i proste sztuczki, dzięki którym zdjęcia maluszka wyjdą miękko i pięknie.",
 "card": "Naturalne światło z okna, pora dnia i proste triki na miękkie, profesjonalne kadry maluszka.",
 "lead": "Światło to najważniejszy element udanego zdjęcia noworodka. Dobra wiadomość: najlepsze jest darmowe i masz je w domu.",
 "secs": [
   {"h2": "Naturalne światło z okna jest najlepsze", "ps": ["Duże okno daje miękkie, rozproszone światło, które pięknie modeluje delikatną buzię. Wyłącz górne lampy — mieszanie świateł daje nieładne, żółte odcienie skóry."]},
   {"h2": "Światło z boku zamiast z przodu", "ps": ["Ustaw maluszka bokiem do okna. Światło padające z boku tworzy delikatny cień i <strong>trójwymiarowość</strong>; światło prosto z przodu spłaszcza twarz."]},
   {"h2": "Złagodź zbyt mocne słońce", "ps": ["Jeśli słońce świeci wprost, zawieś białą firankę lub prześcieradło — rozproszysz światło i unikniesz ostrych cieni oraz przepalonych miejsc."]},
   {"h2": "Unikaj lampy błyskowej", "ps": ["Flesz w telefonie jest twardy i może przestraszyć dziecko. Lepiej podnieś jasność sceny, przysuwając maluszka do okna, niż używać lampy."]},
 ],
},
{
 "cat": "technika",
 "slug": "jak-fotografowac-noworodka-telefonem",
 "title": "Jak fotografować noworodka telefonem — praktyczny poradnik",
 "desc": "Jak zrobić dobre zdjęcia noworodka telefonem? Ustawienia aparatu w smartfonie, ostrość, format i triki, które poprawią jakość zdjęć maluszka.",
 "card": "Ustawienia aparatu w smartfonie, ostrość i format — wyciśnij maksimum z telefonu.",
 "lead": "Współczesny telefon w zupełności wystarczy do pięknych zdjęć noworodka — trzeba tylko wiedzieć, jak go ustawić.",
 "secs": [
   {"h2": "Wyczyść obiektyw i ustaw ostrość na oczy", "ps": ["Przetrzyj obiektyw (często jest zatłuszczony!) i dotknij ekranu w miejscu oczu dziecka, aby aparat ustawił tam ostrość i ekspozycję."]},
   {"h2": "Fotografuj w dobrej jakości", "ps": ["Włącz najwyższą rozdzielczość, a jeśli telefon to oferuje — format <strong>RAW/HEIF</strong>. Unikaj cyfrowego zoomu; zamiast przybliżać, po prostu podejdź bliżej."]},
   {"h2": "Trzymaj telefon stabilnie", "ps": ["Oprzyj łokcie o ciało lub blat, by uniknąć poruszenia. Możesz użyć samowyzwalacza albo poprosić kogoś o pomoc przy podtrzymaniu maluszka."]},
   {"h2": "Rób zdjęcia z góry i z poziomu dziecka", "ps": ["Dwa najlepsze ujęcia to kadr z góry (gdy leży na plecach) i z poziomu jego twarzy. Te perspektywy wyglądają najbardziej naturalnie."]},
 ],
},
{
 "cat": "technika",
 "slug": "najczestsze-bledy-w-zdjeciach-noworodka",
 "title": "Najczęstsze błędy w zdjęciach noworodka (i jak ich uniknąć)",
 "desc": "Rozmyte kadry, żółta skóra, bałagan w tle — poznaj najczęstsze błędy w zdjęciach noworodka i prosty sposób, jak ich uniknąć.",
 "card": "Rozmycie, żółta skóra, bałagan w tle — czego unikać, żeby zdjęcia wyszły dobrze.",
 "lead": "Większość nieudanych zdjęć noworodka to efekt kilku powtarzalnych błędów. Oto te najczęstsze i jak je naprawić.",
 "secs": [
   {"h2": "Złe światło", "ps": ["Zdjęcia robione wieczorem przy żarówce mają żółtą, nienaturalną skórę. Rozwiązanie: fotografuj w dzień, przy oknie."]},
   {"h2": "Bałagan w tle", "ps": ["Kable, pilot, pranie w tle odciągają uwagę. Przed zdjęciem rozejrzyj się po kadrze i usuń wszystko zbędne."]},
   {"h2": "Poruszone, nieostre kadry", "ps": ["Przy słabym świetle telefon wydłuża czas naświetlania i łapie poruszenie. Dodaj światła (okno) i dotknij ekranu, by ustawić ostrość."]},
   {"h2": "Zbyt duży dystans", "ps": ["Maluszek ginie w kadrze. Podejdź bliżej i kadruj ciasno — twarz, dłonie, detale. Resztę (tło, stylizację) możesz dopracować z <a href=\"/poradnik/jak-edytowac-zdjecia-noworodka\">edycją</a> lub w BoboFoto.pl."]},
 ],
},
{
 "cat": "technika",
 "slug": "jak-ustawic-noworodka-do-zdjecia",
 "title": "Jak ułożyć noworodka do zdjęcia — bezpieczne pozy",
 "desc": "Jak bezpiecznie ułożyć noworodka do zdjęcia? Naturalne, bezpieczne pozy dla maluszka w domu — na plecach, na brzuszku rodzica, w zawiniątku.",
 "card": "Naturalne i bezpieczne pozy maluszka, które dobrze wyglądają na zdjęciach.",
 "lead": "Nie musisz układać noworodka w skomplikowane pozy znane z internetu — te wymagają asysty profesjonalisty. W domu najlepiej sprawdzają się proste, bezpieczne ułożenia.",
 "secs": [
   {"h2": "Na plecach, w naturalnej pozycji", "ps": ["Ułóż dziecko na plecach na miękkim, gładkim podłożu i sfotografuj z góry. To najbezpieczniejsze i bardzo urocze ujęcie."]},
   {"h2": "W zawiniątku (otulone)", "ps": ["Delikatnie otulony kocykiem maluszek czuje się bezpiecznie i częściej śpi spokojnie. Otulenie daje też schludny, „studyjny” efekt."]},
   {"h2": "Na ramieniu lub klatce rodzica", "ps": ["Zdjęcie śpiącego dziecka na piersi mamy lub taty to jeden z najpiękniejszych, najbardziej naturalnych kadrów — i w pełni bezpieczny."]},
   {"h2": "Bezpieczeństwo przede wszystkim", "ps": ["<strong>Nigdy</strong> nie układaj noworodka w pozach na podporze bez asekuracji dorosłego. Pozy typu „w dłoniach” na zdjęciach profesjonalistów to często montaż dwóch ujęć."]},
 ],
},
{
 "cat": "technika",
 "slug": "zdjecia-stopek-i-dloni-noworodka",
 "title": "Zdjęcia stópek i dłoni noworodka — jak je pięknie uchwycić",
 "desc": "Jak zrobić piękne zdjęcia stópek i dłoni noworodka? Pomysły na ujęcia detali, makro telefonem i kadry z dłonią rodzica.",
 "card": "Pomysły na wzruszające ujęcia detali — maleńkie stópki, dłonie, rączka w dłoni rodzica.",
 "lead": "Maleńkie stópki i dłonie zmieniają się błyskawicznie — warto je uwiecznić, bo to jedne z najbardziej wzruszających pamiątek.",
 "secs": [
   {"h2": "Podejdź blisko i ustaw ostrość", "ps": ["Zbliż telefon na kilkanaście centymetrów i dotknij ekranu na stópce lub dłoni. Wiele telefonów ma tryb makro do bardzo bliskich kadrów."]},
   {"h2": "Pokaż skalę — dłoń rodzica", "ps": ["Maleńka stópka w dłoni mamy lub taty świetnie oddaje, jak malutkie jest dziecko. To klasyk, który zawsze wzrusza."]},
   {"h2": "Postaw na jednolite tło", "ps": ["Ciemny koc lub jasne prześcieradło pod stópkami sprawią, że detal będzie się wyraźnie odcinał."]},
   {"h2": "Spróbuj wersji czarno-białej", "ps": ["Detale dłoni i stóp wyjątkowo dobrze wyglądają w <a href=\"/poradnik/zdjecia-noworodka-czarno-biale\">czerni i bieli</a> — kolor nie rozprasza, liczy się kształt i faktura."]},
 ],
},
{
 "cat": "technika",
 "slug": "zdjecia-noworodka-czarno-biale",
 "title": "Zdjęcia noworodka czarno-białe — kiedy i jak je robić",
 "desc": "Czarno-białe zdjęcia noworodka wyglądają ponadczasowo. Kiedy warto wybrać czerń i biel, jak je zrobić i co podkreślają takie kadry.",
 "card": "Ponadczasowa czerń i biel — kiedy ją wybrać i jak podkreślić emocje na zdjęciu.",
 "lead": "Czarno-białe zdjęcia noworodka są eleganckie i ponadczasowe — świetnie sprawdzają się na ścianę i do fotoksiążki.",
 "secs": [
   {"h2": "Kiedy czerń i biel działa najlepiej", "ps": ["Gdy chcesz podkreślić <strong>emocje, światło i fakturę</strong> zamiast koloru — np. śpiący maluszek, detale dłoni, zdjęcia z rodzicem."]},
   {"h2": "Dbaj o kontrast i światło", "ps": ["Czarno-białe zdjęcie żyje światłem. Miękkie światło z okna z boku daje piękne przejścia tonalne i głębię."]},
   {"h2": "Ratuje trudne kolory", "ps": ["Jeśli skóra wyszła zaczerwieniona lub tło ma przypadkowe barwy, konwersja na czerń i biel często „naprawia” zdjęcie."]},
   {"h2": "Jak przerobić zdjęcie", "ps": ["W telefonie wystarczy filtr „mono/noir”, a potem lekkie podniesienie kontrastu. W BoboFoto.pl możesz też poprosić o wersję czarno-białą jako jedną ze stylizacji."]},
 ],
},
{
 "cat": "technika",
 "slug": "jak-zrobic-zdjecie-spiacego-noworodka",
 "title": "Jak zrobić zdjęcie śpiącego noworodka",
 "desc": "Jak uchwycić śpiącego noworodka na zdjęciu? Jak go ułożyć, kiedy fotografować i jak nie obudzić maluszka przy robieniu zdjęć.",
 "card": "Jak złapać spokojnego, śpiącego maluszka — timing, cisza i delikatne ułożenie.",
 "lead": "Śpiący noworodek to wymarzony model — spokojny i rozluźniony. Sztuką jest złapać moment, nie budząc go.",
 "secs": [
   {"h2": "Fotografuj po karmieniu", "ps": ["Najedzony i przewinięty maluszek najłatwiej zasypia i śpi głęboko. To najlepsze okno na spokojne zdjęcia."]},
   {"h2": "Wycisz aparat i otoczenie", "ps": ["Wyłącz dźwięk migawki i flesz. Rób zdjęcia w cichym, ciepłym pokoju — chłód i hałas budzą dziecko."]},
   {"h2": "Otul i ułóż wygodnie", "ps": ["Lekko otulony kocykiem maluszek czuje się bezpiecznie i śpi spokojniej, a otulenie ładnie wygląda na zdjęciu."]},
   {"h2": "Działaj spokojnie i bez pośpiechu", "ps": ["Poruszaj się powoli, rób serie cichych zdjęć z różnych ujęć. Nie poprawiaj pozy na siłę — naturalny sen wygląda najpiękniej."]},
 ],
},
{
 "cat": "technika",
 "slug": "jakie-tlo-do-zdjec-noworodka",
 "title": "Jakie tło wybrać do zdjęć noworodka",
 "desc": "Jakie tło najlepiej wygląda na zdjęciach noworodka? Kolory, materiały i proste tła w domu, które podkreślą maluszka, a nie odwrócą uwagi.",
 "card": "Kolory i materiały tła, które podkreślają maluszka zamiast odwracać uwagę.",
 "lead": "Tło potrafi zrobić różnicę między amatorskim a profesjonalnym zdjęciem. Zasada jest prosta: im mniej, tym lepiej.",
 "secs": [
   {"h2": "Stawiaj na stonowane kolory", "ps": ["Beż, biel, kremowy, szałwiowa zieleń, pudrowy róż — neutralne barwy nie rywalizują z dzieckiem i pasują do każdego wnętrza."]},
   {"h2": "Wybieraj gładkie materiały", "ps": ["Jednolity koc, prześcieradło czy narzuta bez wzorów wyglądają najczyściej. Delikatna faktura (bouclé, dzianina) dodaje przytulności."]},
   {"h2": "Unikaj mocnych wzorów", "ps": ["Kolorowe motywy i napisy odciągają wzrok od maluszka i szybko się „starzeją”. Lepiej postawić na ponadczasową prostotę."]},
   {"h2": "Chcesz więcej teł?", "ps": ["W BoboFoto.pl masz do wyboru ponad 30 profesjonalnych teł — od klasyki po sezonowe. Zobacz <a href=\"/poradnik/pomysly-na-stylizacje-zdjec-noworodka\">pomysły na stylizacje</a>."]},
 ],
},
{
 "cat": "technika",
 "slug": "jak-edytowac-zdjecia-noworodka",
 "title": "Jak edytować zdjęcia noworodka — delikatnie i naturalnie",
 "desc": "Jak obrobić zdjęcia noworodka, żeby wyglądały naturalnie? Korekta koloru skóry, jasności i kadru w telefonie — bez przesady.",
 "card": "Delikatna korekta koloru, jasności i kadru — naturalnie, bez przesady.",
 "lead": "Dobra edycja jest niewidoczna — ma podkreślić urok dziecka, a nie zmienić je w plastikową lalkę. Oto złoty środek.",
 "secs": [
   {"h2": "Najpierw wyrównaj kolor skóry", "ps": ["Noworodki bywają zaczerwienione lub mają żółtawy odcień. Lekko obniż nasycenie czerwieni i ustaw naturalny balans bieli, by skóra była zdrowa, nie różowa."]},
   {"h2": "Dopracuj jasność i kadr", "ps": ["Delikatnie rozjaśnij zdjęcie, dodaj odrobinę kontrastu i przytnij kadr, by maluszek był w centrum uwagi."]},
   {"h2": "Nie przesadzaj z wygładzaniem", "ps": ["Meszek i drobne niedoskonałości skóry to urok noworodka. Agresywne wygładzanie wygląda sztucznie — zachowaj naturalność."]},
   {"h2": "Gdy chcesz efekt studyjny", "ps": ["Profesjonalna zmiana tła, stylizacji i światła to coś więcej niż filtr. W <strong>BoboFoto.pl</strong> robimy to za Ciebie, zachowując twarz i rysy dziecka bez zmian."]},
 ],
},
]
