# -*- coding: utf-8 -*-
ITEMS = [
{
 "cat": "poradnik",
 "slug": "sesja-noworodkowa-online-ile-kosztuje",
 "title": "Sesja noworodkowa online — ile kosztuje i jak wygląda?",
 "desc": "Ile kosztuje sesja noworodkowa? Porównujemy tradycyjną sesję (400–600 zł) z sesją online od 9,90 zł i tłumaczymy, jak działa krok po kroku.",
 "card": "Ceny tradycyjnej sesji vs. online i jak odebrać profesjonalne zdjęcia od 9,90 zł.",
 "lead": "Sesja noworodkowa to piękna pamiątka, ale tradycyjnie potrafi sporo kosztować. Sprawdź, ile naprawdę kosztuje i czym różni się od wersji online.",
 "secs": [
   {"h2": "Ile kosztuje tradycyjna sesja", "ps": ["W większości studiów to wydatek <strong>400–600 zł</strong> lub więcej, plus dojazd z noworodkiem i kilka tygodni oczekiwania na zdjęcia."]},
   {"h2": "Ile kosztuje sesja online", "ps": ["W <strong>BoboFoto</strong> ceny zaczynają się od 9,90 zł: Mini 9,90 zł, Standard 29 zł (4 zdjęcia), Premium 49 zł (10 zdjęć). Bez ukrytych kosztów, płatność BLIK lub kartą."]},
   {"h2": "Jak to działa krok po kroku", "ps": ["Robisz w domu jedno zdjęcie, wybierasz tło, płacisz online i odbierasz gotowe zdjęcia — zwykle w około 10 godzin."]},
   {"h2": "Czy wygląda naturalnie", "ps": ["Tak — twarz i rysy dziecka pozostają bez zmian; zmieniamy wyłącznie tło, stylizację i światło, by efekt przypominał sesję studyjną."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "jak-wybrac-fotografa-noworodkowego",
 "title": "Jak wybrać fotografa noworodkowego — na co zwrócić uwagę",
 "desc": "Jak wybrać dobrego fotografa noworodkowego? Portfolio, bezpieczeństwo, cena i terminy — lista rzeczy, które warto sprawdzić przed sesją.",
 "card": "Portfolio, bezpieczeństwo, cena i terminy — co sprawdzić przed wyborem.",
 "lead": "Dobry fotograf noworodkowy to nie tylko ładne portfolio. Oto na co naprawdę warto zwrócić uwagę.",
 "secs": [
   {"h2": "Portfolio i spójny styl", "ps": ["Sprawdź, czy styl zdjęć Ci odpowiada i czy jest spójny — to lepszy wyznacznik niż pojedyncze efektowne kadry."]},
   {"h2": "Bezpieczeństwo dziecka", "ps": ["Upewnij się, że fotograf stawia bezpieczeństwo ponad efektowne pozy i pracuje z asekuracją."]},
   {"h2": "Cena i co obejmuje", "ps": ["Dopytaj, ile zdjęć dostaniesz, czy obróbka jest w cenie i czy nie ma ukrytych opłat za dodatkowe kadry."]},
   {"h2": "Alternatywa: sesja online", "ps": ["Jeśli zależy Ci na wygodzie i niższej cenie, rozważ sesję online — w BoboFoto wiesz z góry, ile zapłacisz i co dostaniesz."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "sesja-noworodkowa-online-czy-warto",
 "title": "Sesja noworodkowa online — czy warto? Zalety i wady",
 "desc": "Czy sesja noworodkowa online się opłaca? Zalety i wady, dla kogo jest idealna i czym różni się od tradycyjnej sesji w studiu.",
 "card": "Zalety i wady sesji online oraz dla kogo to najlepszy wybór.",
 "lead": "Sesja online zyskuje na popularności, ale czy jest dla każdego? Oto uczciwe zestawienie zalet i wad.",
 "secs": [
   {"h2": "Zalety", "ps": ["Brak dojazdu i stresu, komfort domu, niższa cena (od 9,90 zł) i szybka realizacja w ~10 godzin to największe plusy."]},
   {"h2": "Wady", "ps": ["Nie zastąpi fizycznej sesji z profesjonalnym sprzętem na miejscu i zależy od jakości zdjęcia bazowego, które prześlesz."]},
   {"h2": "Dla kogo idealna", "ps": ["Dla rodziców ceniących wygodę i budżet, niechcących wozić noworodka do studia ani czekać tygodniami na efekt."]},
   {"h2": "Jak zacząć", "ps": ["Wystarczy jedno dobre zdjęcie z telefonu. Zobacz, <a href=\"/poradnik/jak-zrobic-zdjecia-noworodka-w-domu\">jak zrobić je w domu</a>, i wybierz stylizację."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "prezent-dla-swiezo-upieczonych-rodzicow",
 "title": "Prezent dla świeżo upieczonych rodziców — pomysły",
 "desc": "Pomysły na prezent dla świeżo upieczonych rodziców: pamiątkowe, praktyczne i wzruszające — w tym profesjonalna sesja zdjęciowa maluszka.",
 "card": "Pamiątkowe i praktyczne pomysły na prezent dla nowych rodziców.",
 "lead": "Szukasz prezentu dla nowych rodziców? Najlepiej trafiają te pamiątkowe — zostają na lata, gdy pieluchy dawno się skończą.",
 "secs": [
   {"h2": "Pamiątkowe", "ps": ["Profesjonalne zdjęcia maluszka, fotoksiążka czy odcisk stópki to prezenty, które wzruszają i zostają na zawsze."]},
   {"h2": "Praktyczne", "ps": ["Kocyki, otulacze, kosz wyprawkowy — przydają się od pierwszego dnia i zawsze są mile widziane."]},
   {"h2": "Dla babci i dziadka", "ps": ["Wydrukowany portret wnuczka w eleganckiej ramce to prezent, który chwyta za serce."]},
   {"h2": "Sesja w prezencie", "ps": ["Profesjonalna sesja online od 9,90 zł to oryginalny, niedrogi i wzruszający pomysł — rodzice sami wybiorą stylizację."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "zdjecia-ciazowe-a-noworodkowe-roznice",
 "title": "Zdjęcia ciążowe a noworodkowe — czym się różnią",
 "desc": "Czym różnią się zdjęcia ciążowe od noworodkowych? Kiedy je robić, jak się przygotować i jak połączyć obie pamiątki w spójną historię.",
 "card": "Kiedy robić, jak przygotować i jak połączyć obie sesje w spójną historię.",
 "lead": "Sesja ciążowa i noworodkowa to dwa rozdziały tej samej, pięknej historii. Oto czym się różnią i jak je połączyć.",
 "secs": [
   {"h2": "Sesja ciążowa", "ps": ["Najlepiej robić ją w 7.–8. miesiącu, gdy brzuszek jest okrągły, a mama wciąż czuje się komfortowo."]},
   {"h2": "Sesja noworodkowa", "ps": ["Powstaje po narodzinach i skupia się na maluszku — jego rysach, detalach i pierwszych chwilach z rodziną."]},
   {"h2": "Spójna stylizacja", "ps": ["Zachowanie podobnej kolorystyki i klimatu sprawi, że obie sesje będą tworzyć jedną, ładną opowieść."]},
   {"h2": "Połącz je w album", "ps": ["Zestawienie brzuszka i noworodka w jednej fotoksiążce to wzruszająca pamiątka. Spójne kadry przygotujesz w BoboFoto."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "jak-zamowic-sesje-noworodkowa-online",
 "title": "Jak zamówić sesję noworodkową online — krok po kroku",
 "desc": "Jak zamówić sesję noworodkową online w BoboFoto? Prosty proces krok po kroku: zdjęcie, wybór tła, płatność i odbiór gotowych zdjęć.",
 "card": "Prosty proces krok po kroku: zdjęcie, tło, płatność i odbiór zdjęć.",
 "lead": "Zamówienie sesji online jest banalnie proste i zajmuje kilka minut. Oto cały proces krok po kroku.",
 "secs": [
   {"h2": "1. Zrób zdjęcie w domu", "ps": ["Wystarczy jedno dobre zdjęcie maluszka z telefonu — najlepiej przy świetle z okna."]},
   {"h2": "2. Wybierz tło i stylizację", "ps": ["Z galerii ponad 30 stylów wybierasz te, które Ci się podobają, albo opisujesz, czego potrzebujesz."]},
   {"h2": "3. Zapłać online", "ps": ["Wybierasz pakiet (od 9,90 zł) i płacisz wygodnie BLIK-iem lub kartą. Bez ukrytych kosztów."]},
   {"h2": "4. Odbierz gotowe zdjęcia", "ps": ["Profesjonalnie przygotowane kadry dostajesz zwykle w około 10 godzin. <a href=\"/#cennik\">Zobacz pakiety i zamów</a>."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "czy-zdjecia-ai-noworodka-sa-bezpieczne",
 "title": "Czy zdjęcia noworodka online są bezpieczne dla prywatności?",
 "desc": "Czy przesyłanie zdjęć noworodka do obróbki online jest bezpieczne? Jak chronione są dane i zdjęcia dziecka oraz na co zwracać uwagę (RODO).",
 "card": "Jak chronione są zdjęcia i dane dziecka przy sesji online — i na co uważać.",
 "lead": "Prywatność dziecka jest najważniejsza. Wyjaśniamy, jak bezpiecznie korzystać z sesji online i o co warto pytać.",
 "secs": [
   {"h2": "Sprawdź politykę prywatności", "ps": ["Rzetelna firma jasno opisuje, jak przetwarza zdjęcia i dane — zgodnie z RODO. Zobacz naszą <a href=\"/polityka-prywatnosci\">politykę prywatności</a>."]},
   {"h2": "Zdjęcia tylko do realizacji", "ps": ["W BoboFoto przesłane zdjęcia wykorzystujemy wyłącznie do przygotowania Twojego zamówienia."]},
   {"h2": "Bezpieczne przesyłanie i płatność", "ps": ["Dane przesyłane są bezpiecznym połączeniem, a płatności obsługuje zaufany operator (BLIK, karta)."]},
   {"h2": "Twoja kontrola", "ps": ["Decydujesz, jakie zdjęcie wysyłasz, a my zmieniamy tylko tło i stylizację — twarz i rysy dziecka pozostają bez zmian."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "zdjecia-noworodka-dla-babci-i-dziadka",
 "title": "Zdjęcia noworodka dla babci i dziadka — pomysły na prezent",
 "desc": "Jak sprawić radość dziadkom? Pomysły na zdjęcia noworodka dla babci i dziadka: portret w ramce, fotoksiążka i pamiątkowe wydruki.",
 "card": "Portret w ramce, fotoksiążka, wydruki — jak ucieszyć dziadków zdjęciami wnuczka.",
 "lead": "Nic nie cieszy dziadków tak, jak zdjęcia wnuczka. To prezent, który chwyta za serce niezależnie od okazji.",
 "secs": [
   {"h2": "Portret w eleganckiej ramce", "ps": ["Klasyczny, stonowany portret maluszka w ramce to ozdoba salonu i prezent na lata."]},
   {"h2": "Mała fotoksiążka", "ps": ["Album z pierwszych tygodni to wzruszająca pamiątka, do której dziadkowie będą wracać."]},
   {"h2": "Kadr okolicznościowy", "ps": ["Świąteczna lub urodzinowa stylizacja sprawi, że prezent będzie pasował do konkretnej okazji."]},
   {"h2": "Szybko i bez wychodzenia z domu", "ps": ["W BoboFoto z domowego zdjęcia przygotujesz piękny portret do druku — w ~10 godzin."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "najlepsze-pamiatki-z-pierwszych-dni-dziecka",
 "title": "Najlepsze pamiątki z pierwszych dni dziecka",
 "desc": "Najpiękniejsze pamiątki z pierwszych dni dziecka: zdjęcia, odcisk stópki, opaska ze szpitala i fotoksiążka. Pomysły, by zatrzymać ten czas.",
 "card": "Zdjęcia, odcisk stópki, fotoksiążka — jak zatrzymać pierwsze dni maluszka.",
 "lead": "Pierwsze dni mijają błyskawicznie. Warto zatrzymać je w pamiątkach, do których będziecie wracać przez całe życie.",
 "secs": [
   {"h2": "Profesjonalne zdjęcia", "ps": ["To najważniejsza pamiątka — uwieczniają, jak malutkie i kruche było dziecko na samym początku."]},
   {"h2": "Odcisk stópki i dłoni", "ps": ["Gipsowy lub tuszowy odcisk maleńkiej stópki to wzruszający, trójwymiarowy ślad pierwszych dni."]},
   {"h2": "Pamiątki ze szpitala", "ps": ["Opaska identyfikacyjna, pierwszy czepek czy metryczka — drobiazgi, które nabierają ogromnej wartości."]},
   {"h2": "Fotoksiążka łącząca wszystko", "ps": ["Album z najlepszymi zdjęciami spina pierwsze tygodnie w jedną, trwałą opowieść. Dobre kadry przygotujesz w BoboFoto."]},
 ],
},
{
 "cat": "poradnik",
 "slug": "ile-kosztuje-fotograf-noworodkowy-w-polsce",
 "title": "Ile kosztuje fotograf noworodkowy w Polsce",
 "desc": "Ile kosztuje fotograf noworodkowy w Polsce? Realne ceny sesji w studiu, co wpływa na koszt i tańsza alternatywa — sesja online od 9,90 zł.",
 "card": "Realne ceny sesji w studiu, co wpływa na koszt i tańsza alternatywa online.",
 "lead": "Ceny fotografów noworodkowych potrafią się mocno różnić. Oto czego się spodziewać i jak zmieścić się w budżecie.",
 "secs": [
   {"h2": "Typowe ceny w studiu", "ps": ["Sesja noworodkowa w Polsce to najczęściej <strong>400–600 zł</strong>, a w dużych miastach i u znanych fotografów nawet więcej."]},
   {"h2": "Co wpływa na cenę", "ps": ["Liczba gotowych zdjęć, czas obróbki, dodatkowe stylizacje, dojazd i renoma fotografa — to wszystko podnosi koszt."]},
   {"h2": "Tańsza alternatywa", "ps": ["Sesja online w BoboFoto zaczyna się od 9,90 zł, bez dojazdu i ukrytych opłat — znasz cenę z góry."]},
   {"h2": "Na co zwrócić uwagę", "ps": ["Zawsze sprawdź, ile zdjęć i jaka obróbka są w cenie. Zobacz też, <a href=\"/poradnik/jak-wybrac-fotografa-noworodkowego\">jak wybrać fotografa</a>."]},
 ],
},
]
