# -*- coding: utf-8 -*-
ITEMS = [
{
 "cat": "okazje",
 "slug": "swiateczne-zdjecia-noworodka-pierwsze-swieta",
 "title": "Świąteczne zdjęcia noworodka — pomysły na pierwsze święta",
 "desc": "Pierwsze święta z noworodkiem to wyjątkowa okazja. Pomysły na świąteczne zdjęcia maluszka: stylizacje, tła i kadry na kartki dla rodziny.",
 "card": "Pomysły na pierwsze święta maluszka — stylizacje, tła i kadry idealne na kartki.",
 "lead": "Pierwsze święta dziecka zdarzają się tylko raz. Świąteczne zdjęcia to wzruszająca pamiątka i idealny prezent dla babci i dziadka.",
 "secs": [
   {"h2": "Stylizacja małego elfa lub aniołka", "ps": ["Czapeczka elfa, miękki kocyk w świątecznych barwach albo delikatne skrzydełka aniołka tworzą urocze, ciepłe kadry."]},
   {"h2": "Ciepłe, świąteczne tła", "ps": ["Stonowana zieleń, złoto i czerwień, miękkie światełka w tle (bokeh) budują magiczny, świąteczny nastrój bez przesady."]},
   {"h2": "Zrób kadr na kartkę świąteczną", "ps": ["Zostaw w kadrze trochę miejsca na życzenia — taką kartkę z maluszkiem rodzina będzie przechowywać latami."]},
   {"h2": "Nie masz czasu na sesję w studiu?", "ps": ["W <strong>BoboFoto.pl</strong> wyślesz jedno domowe zdjęcie i wybierzesz świąteczną stylizację — gotowe w ~10 godzin, w sam raz przed świętami."]},
 ],
},
{
 "cat": "okazje",
 "slug": "sesja-noworodkowa-zima",
 "title": "Sesja noworodkowa zimą — pomysły i stylizacje",
 "desc": "Zimowa sesja noworodkowa: przytulne stylizacje, ciepłe tła i pomysły na zdjęcia maluszka urodzonego zimą. Inspiracje dla rodziców.",
 "card": "Przytulne, zimowe stylizacje i ciepłe tła dla maluszka urodzonego w chłodne miesiące.",
 "lead": "Zima to czas ciepłych kocyków, miękkich czapeczek i przytulnych kadrów. Idealna sceneria na pierwsze zdjęcia maluszka.",
 "secs": [
   {"h2": "Postaw na przytulność", "ps": ["Miękkie dzianiny, futrzane kocyki i czapeczki z uszkami budują ciepły, zimowy klimat i podkreślają kruchość noworodka."]},
   {"h2": "Zimowa kolorystyka", "ps": ["Biel, szarości, srebro i chłodne błękity świetnie oddają zimową aurę, a jednocześnie pozostają eleganckie i ponadczasowe."]},
   {"h2": "Ciepło i bezpieczeństwo", "ps": ["W domu zadbaj o ciepło w pokoju — maluszek szybko się wychładza. Zdjęcia rób krótko i z przerwami."]},
   {"h2": "Zimowa stylizacja bez wychodzenia z domu", "ps": ["Nie musisz wozić noworodka w mróz do studia — w BoboFoto.pl wybierzesz zimowe tło online, a efekt odbierzesz tego samego dnia."]},
 ],
},
{
 "cat": "okazje",
 "slug": "zdjecia-noworodka-na-wielkanoc",
 "title": "Zdjęcia noworodka na Wielkanoc — wiosenne pomysły",
 "desc": "Wielkanocne zdjęcia noworodka: delikatne pastele, wiosenne motywy i pomysły na urocze kadry maluszka na Wielkanoc.",
 "card": "Pastelowe, wiosenne motywy wielkanocne — delikatne i urocze kadry maluszka.",
 "lead": "Wielkanoc to święto wiosny i nowego życia — idealny moment na delikatne, pastelowe zdjęcia maluszka.",
 "secs": [
   {"h2": "Pastelowa kolorystyka", "ps": ["Pudrowy róż, miętowa zieleń, kremowa biel i delikatny żółty budują lekki, wiosenny nastrój."]},
   {"h2": "Wiosenne motywy", "ps": ["Delikatne kwiaty, miękkie kocyki i naturalne, jasne światło tworzą świeży, radosny klimat Wielkanocy."]},
   {"h2": "Kadr dla rodziny", "ps": ["Wielkanocne zdjęcie maluszka to piękny akcent na świątecznym stole i miły gest dla bliskich."]},
   {"h2": "Gotowe na święta w jeden dzień", "ps": ["W BoboFoto.pl wybierzesz wielkanocną stylizację online i odbierzesz gotowe zdjęcia w ~10 godzin."]},
 ],
},
{
 "cat": "okazje",
 "slug": "jesienna-sesja-noworodkowa",
 "title": "Jesienna sesja noworodkowa — ciepłe barwy i pomysły",
 "desc": "Jesienna sesja noworodkowa: ciepłe, ziemiste barwy, motyw dyni i przytulne stylizacje dla maluszka urodzonego jesienią.",
 "card": "Ciepłe, ziemiste barwy i przytulne motywy jesienne dla maluszka.",
 "lead": "Jesień to ciepłe światło i przytulne barwy — wymarzona sceneria na nastrojowe zdjęcia noworodka.",
 "secs": [
   {"h2": "Ziemista paleta", "ps": ["Rdzawe pomarańcze, musztarda, brąz i ciepła biel oddają jesienny klimat i pięknie współgrają z delikatną skórą."]},
   {"h2": "Motyw dyni i natury", "ps": ["Delikatny akcent dyni czy suszonych liści dodaje sezonowego charakteru — w wersji minimalistycznej, by nie przytłoczyć maluszka."]},
   {"h2": "Ciepłe, miękkie światło", "ps": ["Jesienne, niskie słońce daje piękne, złote światło — fotografuj przy oknie w godzinach przedpołudniowych."]},
   {"h2": "Jesienna stylizacja online", "ps": ["W BoboFoto.pl dobierzesz jesienne tło do domowego zdjęcia i odbierzesz profesjonalny efekt tego samego dnia."]},
 ],
},
{
 "cat": "okazje",
 "slug": "wiosenna-sesja-noworodkowa",
 "title": "Wiosenna sesja noworodkowa — świeże, jasne kadry",
 "desc": "Wiosenna sesja noworodkowa: jasne kolory, kwiatowe motywy i świeże, delikatne kadry dla maluszka urodzonego wiosną.",
 "card": "Jasne kolory i kwiatowe motywy — świeże, delikatne kadry maluszka.",
 "lead": "Wiosna kojarzy się z lekkością i nowym początkiem — to idealny nastrój na pierwsze zdjęcia dziecka.",
 "secs": [
   {"h2": "Jasna, świeża paleta", "ps": ["Biel, pastele i delikatna zieleń budują lekki, wiosenny klimat pełen świeżości."]},
   {"h2": "Kwiatowe akcenty", "ps": ["Drobne kwiaty czy delikatne wianki to urocze dodatki — w subtelnej ilości, by maluszek pozostał w centrum."]},
   {"h2": "Naturalne światło", "ps": ["Wiosenne światło jest jasne i miękkie — ustaw dziecko przy oknie i unikaj sztucznych lamp."]},
   {"h2": "Wiosenny efekt bez studia", "ps": ["W BoboFoto.pl wybierzesz wiosenne tło online i odbierzesz gotowe zdjęcia w ~10 godzin."]},
 ],
},
{
 "cat": "okazje",
 "slug": "letnia-sesja-noworodkowa",
 "title": "Letnia sesja noworodkowa — lekko i naturalnie",
 "desc": "Letnia sesja noworodkowa: lekkie, jasne stylizacje i naturalne kadry dla maluszka urodzonego latem. Pomysły i wskazówki.",
 "card": "Lekkie, jasne stylizacje i naturalne kadry dla letniego maluszka.",
 "lead": "Lato to lekkość, jasność i mnóstwo naturalnego światła — wdzięczna pora na delikatne zdjęcia noworodka.",
 "secs": [
   {"h2": "Lekkie, przewiewne stylizacje", "ps": ["Cienka bawełna, len i jasne barwy oddają letni, naturalny klimat i nie przegrzewają maluszka."]},
   {"h2": "Uważaj na mocne słońce", "ps": ["Latem słońce bywa ostre — fotografuj przy oknie z firanką lub w cieniu, by uniknąć twardych cieni i przegrzania dziecka."]},
   {"h2": "Naturalne, świetliste kadry", "ps": ["Jasne, przewiewne tła i delikatne światło dają radosny, wakacyjny nastrój."]},
   {"h2": "Letnia stylizacja w jeden dzień", "ps": ["W BoboFoto.pl dobierzesz letnie tło do domowego zdjęcia i odbierzesz efekt tego samego dnia."]},
 ],
},
{
 "cat": "okazje",
 "slug": "zdjecia-na-roczek-dziecka",
 "title": "Zdjęcia na roczek dziecka — pomysły na pierwsze urodziny",
 "desc": "Zdjęcia na roczek dziecka: pomysły na sesję z okazji pierwszych urodzin, stylizacje, tort i kadry, które warto uwiecznić.",
 "card": "Pomysły na sesję z okazji pierwszych urodzin — stylizacje i kadry roczku.",
 "lead": "Pierwsze urodziny to wielkie święto. Roczkowa sesja to piękne zamknięcie pierwszego, najszybszego roku życia dziecka.",
 "secs": [
   {"h2": "Klasyczna sesja roczkowa", "ps": ["Proste tło, ulubiona zabawka i naturalne kadry uśmiechu — to przepis na ponadczasowe zdjęcia z roczku."]},
   {"h2": "Motyw tortu (smash the cake)", "ps": ["Zdjęcia z małym tortem, który dziecko z radością rozgniata, to świetna zabawa i mnóstwo emocji w kadrze."]},
   {"h2": "Porównanie z noworodkiem", "ps": ["Zestaw zdjęcie z roczku z fotografią z pierwszych dni — pokazuje, jak bardzo dziecko urosło."]},
   {"h2": "Stylizacje na roczek online", "ps": ["W BoboFoto.pl przygotujesz piękne, urodzinowe kadry na podstawie domowego zdjęcia, bez stresu sesji w studiu."]},
 ],
},
{
 "cat": "okazje",
 "slug": "zdjecia-z-chrztu-pomysly",
 "title": "Zdjęcia z chrztu dziecka — pomysły na pamiątkowe kadry",
 "desc": "Pomysły na zdjęcia z chrztu dziecka: stylizacje, eleganckie tła i pamiątkowe kadry, które warto uwiecznić na ten wyjątkowy dzień.",
 "card": "Eleganckie, pamiątkowe kadry na chrzest — stylizacje i pomysły.",
 "lead": "Chrzest to jedno z najważniejszych rodzinnych wydarzeń. Warto mieć z niego piękne, eleganckie zdjęcia maluszka.",
 "secs": [
   {"h2": "Elegancka, jasna stylizacja", "ps": ["Biel i delikatne, kremowe odcienie podkreślają uroczysty charakter dnia i pięknie wyglądają na pamiątkowych zdjęciach."]},
   {"h2": "Detale ubranka", "ps": ["Sfotografuj haftowaną szatkę, czepek czy świecę chrzcielną — te detale tworzą wzruszającą pamiątkę."]},
   {"h2": "Kadr z rodzicami i chrzestnymi", "ps": ["Wspólne, spokojne ujęcie z najbliższymi to zdjęcie, które trafi do rodzinnego albumu na lata."]},
   {"h2": "Pamiątkowy portret maluszka", "ps": ["Z domowego zdjęcia w eleganckiej stylizacji stworzysz w BoboFoto.pl portret idealny na pamiątkę chrztu."]},
 ],
},
{
 "cat": "okazje",
 "slug": "walentynkowe-zdjecia-dziecka",
 "title": "Walentynkowe zdjęcia dziecka — słodkie pomysły",
 "desc": "Walentynkowe zdjęcia dziecka: słodkie, czerwono-różowe motywy i pomysły na urocze kadry maluszka na walentynki.",
 "card": "Słodkie, czerwono-różowe motywy na walentynki — urocze kadry maluszka.",
 "lead": "Walentynki to okazja na pełne czułości, słodkie zdjęcia maluszka — symbol największej miłości w rodzinie.",
 "secs": [
   {"h2": "Czerwień i róż w tle", "ps": ["Delikatne odcienie czerwieni i różu oraz motyw serc budują ciepły, walentynkowy nastrój."]},
   {"h2": "Motyw serca i czułości", "ps": ["Dłonie rodziców układające serce wokół maluszka albo kocyk z serduszkami to urocze, symboliczne kadry."]},
   {"h2": "Stawiaj na delikatność", "ps": ["Mniej znaczy więcej — subtelne akcenty wyglądają lepiej niż przeładowana dekoracja."]},
   {"h2": "Walentynkowa stylizacja online", "ps": ["W BoboFoto.pl przygotujesz słodką, walentynkową wersję domowego zdjęcia w ~10 godzin."]},
 ],
},
{
 "cat": "okazje",
 "slug": "zdjecia-noworodka-na-halloween",
 "title": "Zdjęcia noworodka na Halloween — urocze, nie straszne",
 "desc": "Pomysły na zdjęcia noworodka na Halloween: urocze, delikatne stylizacje (dynia, mały duszek) zamiast strasznych motywów.",
 "card": "Urocze, łagodne stylizacje na Halloween — dynia, mały duszek, ciepłe barwy.",
 "lead": "Halloweenowe zdjęcia maluszka mogą być urocze, a nie straszne — to świetna zabawa i sezonowa pamiątka.",
 "secs": [
   {"h2": "Słodkie kostiumy zamiast straszaków", "ps": ["Mała dynia, delikatny duszek czy kostium zwierzątka wyglądają uroczo i nie przestraszą dziecka."]},
   {"h2": "Ciepła, jesienna paleta", "ps": ["Pomarańcz, brąz i ciepła biel pasują do Halloween i jednocześnie pozostają delikatne."]},
   {"h2": "Zachowaj umiar", "ps": ["Jeden wyrazisty akcent (np. czapeczka-dynia) wystarczy — maluszek powinien pozostać w centrum kadru."]},
   {"h2": "Halloweenowy kadr online", "ps": ["W BoboFoto.pl dobierzesz sezonową stylizację do domowego zdjęcia i odbierzesz efekt tego samego dnia."]},
 ],
},
]
