# -*- coding: utf-8 -*-
ITEMS = [
{
 "cat": "praktyka",
 "slug": "kiedy-zrobic-sesje-noworodkowa",
 "title": "Kiedy zrobić sesję noworodkową — najlepszy moment",
 "desc": "Kiedy najlepiej zrobić sesję noworodkową? Optymalny wiek dziecka, dlaczego pierwsze dni są wyjątkowe i co zrobić, gdy ten moment minął.",
 "card": "Optymalny wiek dziecka na sesję i co zrobić, gdy ten moment już minął.",
 "lead": "Pytanie „kiedy zrobić sesję noworodkową” zadaje sobie większość rodziców. Oto co warto wiedzieć o najlepszym momencie.",
 "secs": [
   {"h2": "Klasycznie: pierwsze 5–14 dni", "ps": ["W tym czasie noworodki dużo śpią i łatwo układają się w „zwinięte” pozy z brzuszka. Dlatego studia polecają ten okres na klasyczną sesję."]},
   {"h2": "Ale później też jest pięknie", "ps": ["Po 2–3 tygodniach maluszek bywa bardziej wybudzony, ale zdjęcia wcale nie są gorsze — łapiesz więcej mimiki i otwarte oczka."]},
   {"h2": "Gdy moment minął", "ps": ["Nie martw się, jeśli pierwsze dni przeleciały. Każdy etap jest wyjątkowy, a piękne zdjęcie zrobisz w dowolnym momencie."]},
   {"h2": "Sesja online bez presji czasu", "ps": ["W <strong>BoboFoto.pl</strong> nie musisz łapać konkretnego dnia ani umawiać terminu — robisz zdjęcie w domu, kiedy maluszek jest spokojny, a my robimy resztę."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "jak-przygotowac-noworodka-do-sesji",
 "title": "Jak przygotować noworodka do sesji zdjęciowej",
 "desc": "Jak przygotować noworodka do sesji? Karmienie, pora dnia, ciepło i spokój — praktyczna checklista, dzięki której zdjęcia się udadzą.",
 "card": "Karmienie, pora dnia, ciepło i spokój — checklista przed udanymi zdjęciami.",
 "lead": "Dobre przygotowanie to połowa sukcesu. Zadbany, najedzony i spokojny maluszek pozwoli zrobić piękne zdjęcia bez stresu.",
 "secs": [
   {"h2": "Nakarm tuż przed zdjęciami", "ps": ["Najedzony noworodek jest senny i zadowolony — to najlepszy stan na spokojne kadry."]},
   {"h2": "Wybierz porę największego spokoju", "ps": ["Obserwuj rytm dziecka i wybierz porę, gdy zwykle jest najedzone i wyspane (często przedpołudnie)."]},
   {"h2": "Zadbaj o ciepło", "ps": ["W pokoju powinno być cieplej niż zwykle, zwłaszcza przy zdjęciach bez ubranka. Chłód to główny powód płaczu."]},
   {"h2": "Przygotuj scenę wcześniej", "ps": ["Rozłóż koc, ustaw światło i miej pod ręką chusteczki oraz zapasowe ubranko, by nie tracić cennych minut spokoju."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "ile-trwa-sesja-noworodkowa",
 "title": "Ile trwa sesja noworodkowa",
 "desc": "Ile trwa sesja noworodkowa? Czas tradycyjnej sesji w studiu, od czego zależy i ile zajmuje sesja online. Praktyczne info dla rodziców.",
 "card": "Ile czasu zajmuje sesja w studiu, a ile online — i od czego to zależy.",
 "lead": "Czas sesji noworodkowej zależy głównie od maluszka. Oto czego się spodziewać przy sesji tradycyjnej i online.",
 "secs": [
   {"h2": "Tradycyjna sesja: 2–4 godziny", "ps": ["W studiu sesja trwa zwykle kilka godzin, bo trzeba robić przerwy na karmienie, przewijanie i uspokajanie dziecka."]},
   {"h2": "Od czego zależy czas", "ps": ["Im spokojniejszy maluszek i im mniej zmian stylizacji, tym szybciej. Płacz i głód potrafią wydłużyć sesję."]},
   {"h2": "Sesja online: kilka minut Twojego czasu", "ps": ["Wysłanie zdjęcia i wybór tła zajmuje dosłownie chwilę — bez wielogodzinnego siedzenia z dzieckiem w studiu."]},
   {"h2": "Realizacja w ~10 godzin", "ps": ["W <strong>BoboFoto.pl</strong> gotowe zdjęcia odbierasz zwykle w około 10 godzin od wysłania, a w pakiecie Premium priorytetowo."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "bezpieczenstwo-podczas-sesji-noworodkowej",
 "title": "Bezpieczeństwo podczas sesji noworodkowej",
 "desc": "Bezpieczeństwo na sesji noworodkowej: zasady asekuracji, prawda o trudnych pozach i jak robić zdjęcia maluszka bez ryzyka.",
 "card": "Zasady asekuracji i prawda o „trudnych pozach” — jak fotografować bez ryzyka.",
 "lead": "Żadne zdjęcie nie jest warte ryzyka. Oto najważniejsze zasady bezpiecznej fotografii noworodkowej.",
 "secs": [
   {"h2": "Zawsze asekuruj dziecko", "ps": ["Dorosły powinien być w zasięgu ręki przez cały czas, zwłaszcza przy zdjęciach w koszu czy na podwyższeniu."]},
   {"h2": "Prawda o efektownych pozach", "ps": ["Pozy typu „w dłoniach” czy „na rączkach” widoczne online to często <strong>montaż kilku ujęć</strong>. Nie próbuj ich odtwarzać samodzielnie."]},
   {"h2": "Komfort termiczny", "ps": ["Ciepły pokój i krótkie sesje chronią maluszka przed wychłodzeniem."]},
   {"h2": "Słuchaj dziecka", "ps": ["Jeśli noworodek protestuje — przerwij. Zrelaksowane dziecko zawsze wyjdzie na zdjęciu lepiej niż zestresowane."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "jak-uspokoic-noworodka-podczas-sesji",
 "title": "Jak uspokoić noworodka podczas robienia zdjęć",
 "desc": "Jak uspokoić i uśpić noworodka do zdjęć? Sprawdzone sposoby: otulanie, biały szum, karmienie i ciepło. Praktyczne triki dla rodziców.",
 "card": "Otulanie, biały szum, karmienie, ciepło — sprawdzone sposoby na spokój maluszka.",
 "lead": "Spokojny maluszek to udane zdjęcia. Oto sprawdzone sposoby, by go wyciszyć i uśpić podczas sesji.",
 "secs": [
   {"h2": "Otulanie", "ps": ["Delikatne owinięcie kocykiem daje poczucie bezpieczeństwa jak w brzuszku i często szybko wycisza."]},
   {"h2": "Biały szum", "ps": ["Szum suszarki, aplikacji lub kołysanki przypomina dźwięki sprzed narodzin i pomaga zasnąć."]},
   {"h2": "Karmienie i ciepło", "ps": ["Najedzony maluszek w ciepłym pokoju zasypia najłatwiej. Czasem wystarczy chwila przytulenia tuż przed zdjęciem."]},
   {"h2": "Cierpliwość i spokój", "ps": ["Działaj powoli i bez nerwów — dzieci wyczuwają napięcie. Zaplanuj zapas czasu, by niczego nie robić w pośpiechu."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "co-ubrac-na-sesje-rodzinna-z-noworodkiem",
 "title": "Co ubrać na sesję rodzinną z noworodkiem",
 "desc": "Co założyć na sesję rodzinną z noworodkiem? Jak dobrać spójne, stonowane stroje dla całej rodziny, by zdjęcia wyglądały elegancko.",
 "card": "Jak dobrać spójne, stonowane stroje całej rodziny do wspólnych kadrów.",
 "lead": "Spójne stroje sprawiają, że rodzinne zdjęcie wygląda elegancko i ponadczasowo. Oto jak je dobrać bez wysiłku.",
 "secs": [
   {"h2": "Wspólna, stonowana paleta", "ps": ["Wybierzcie 2–3 spójne kolory (np. beż, biel, szałwia) i trzymajcie się ich — unikajcie mocnych wzorów i napisów."]},
   {"h2": "Komfort i naturalność", "ps": ["Wygodne ubrania, w których czujecie się dobrze, dają najbardziej naturalne kadry. Sztywne, nowe stroje krępują."]},
   {"h2": "Maluszek w centrum", "ps": ["Stroje rodziców powinny być tłem dla dziecka — stonowane, by uwaga skupiła się na noworodku."]},
   {"h2": "Spójna oprawa kadru", "ps": ["W BoboFoto.pl dopasujemy tło do Waszych strojów, by całość wyglądała jak profesjonalna sesja rodzinna."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "sesja-noworodkowa-w-domu-czy-w-studiu",
 "title": "Sesja noworodkowa w domu czy w studiu — co wybrać",
 "desc": "Sesja noworodkowa w domu czy w studiu? Porównanie wygody, kosztów, komfortu dziecka i jakości zdjęć. Plus trzecia opcja: sesja online.",
 "card": "Porównanie: wygoda, koszt i komfort dziecka — plus trzecia opcja, czyli online.",
 "lead": "Dom czy studio? Każda opcja ma plusy i minusy. Jest też trzecia droga, która łączy wygodę domu z efektem studia.",
 "secs": [
   {"h2": "Sesja w studiu", "ps": ["Profesjonalne tła i światło, ale dojazd z noworodkiem, wyższy koszt (zwykle 400–600 zł) i obce otoczenie dla dziecka."]},
   {"h2": "Sesja w domu", "ps": ["Komfort i spokój maluszka oraz brak dojazdu, ale trudniej o studyjne tło i profesjonalne światło."]},
   {"h2": "Trzecia opcja: sesja online", "ps": ["Robisz zdjęcie w domu, a profesjonalne tło i światło dokładamy my. Łączysz wygodę domu z efektem studia — od 24 zł."]},
   {"h2": "Co wybrać", "ps": ["Jeśli zależy Ci na świętym spokoju, niskim koszcie i szybkim efekcie — sprawdź <a href=\"/poradnik/sesja-noworodkowa-online-ile-kosztuje\">sesję noworodkową online</a>."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "jak-przechowywac-zdjecia-dziecka",
 "title": "Jak bezpiecznie przechowywać zdjęcia dziecka",
 "desc": "Jak przechowywać i archiwizować zdjęcia dziecka, by ich nie stracić? Kopie zapasowe, chmura i porządkowanie zdjęć — praktyczny poradnik.",
 "card": "Kopie zapasowe, chmura i porządek — żeby nigdy nie stracić zdjęć dziecka.",
 "lead": "Zdjęcia z pierwszych dni są bezcenne i niepowtarzalne. Warto zadbać, by nigdy nie przepadły wraz z zepsutym telefonem.",
 "secs": [
   {"h2": "Zasada 3 kopii", "ps": ["Trzymaj zdjęcia w co najmniej trzech miejscach: telefon, dysk/komputer i chmura. Jedna awaria nie pozbawi Cię wtedy wszystkiego."]},
   {"h2": "Korzystaj z chmury", "ps": ["Automatyczny backup do chmury (np. Google Zdjęcia, iCloud) chroni przed zgubieniem lub uszkodzeniem telefonu."]},
   {"h2": "Porządkuj na bieżąco", "ps": ["Twórz albumy „pierwszy miesiąc”, „roczek” itd. Łatwiej potem odnaleźć ulubione kadry."]},
   {"h2": "Wydrukuj najważniejsze", "ps": ["Wydruk lub fotoksiążka przetrwają każdą awarię sprzętu — to najbezpieczniejsza forma pamiątki."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "jak-zrobic-fotoksiazke-z-noworodkiem",
 "title": "Jak zrobić fotoksiążkę z noworodkiem",
 "desc": "Jak stworzyć piękną fotoksiążkę z pierwszych dni dziecka? Wybór zdjęć, układ, format i wskazówki na ponadczasową pamiątkę.",
 "card": "Wybór zdjęć, układ i format — jak złożyć ponadczasową fotoksiążkę maluszka.",
 "lead": "Fotoksiążka to najpiękniejszy sposób, by zamknąć pierwsze tygodnie dziecka w jednej, trwałej pamiątce.",
 "secs": [
   {"h2": "Wybierz najlepsze kadry", "ps": ["Postaw na jakość, nie ilość — 20–40 naprawdę dobrych zdjęć zrobi większe wrażenie niż setki podobnych."]},
   {"h2": "Opowiedz historię", "ps": ["Ułóż zdjęcia chronologicznie: przyjazd do domu, detale, sen, pierwsze chwile z rodziną. To tworzy narrację."]},
   {"h2": "Zadbaj o spójność", "ps": ["Spójna stylizacja i kolorystyka zdjęć sprawiają, że album wygląda profesjonalnie i elegancko."]},
   {"h2": "Dobre zdjęcia to podstawa", "ps": ["Im lepsze kadry, tym piękniejsza książka. Profesjonalne wersje przygotujesz szybko w BoboFoto.pl."]},
 ],
},
{
 "cat": "praktyka",
 "slug": "ile-zdjec-z-sesji-noworodkowej-wybrac",
 "title": "Ile zdjęć z sesji noworodkowej wybrać",
 "desc": "Ile zdjęć z sesji noworodkowej wybrać do druku i albumu? Jak nie utonąć w wyborze i postawić na najlepsze, różnorodne kadry.",
 "card": "Jak nie utonąć w wyborze i postawić na najlepsze, różnorodne kadry.",
 "lead": "Wybór ulubionych zdjęć bywa trudniejszy niż sama sesja. Oto jak podejść do tego rozsądnie.",
 "secs": [
   {"h2": "Stawiaj na różnorodność", "ps": ["Wybierz kilka typów kadrów: portret, detale (dłonie, stópki), zdjęcie z rodzicem, ujęcie całej sylwetki. Album będzie ciekawszy."]},
   {"h2": "Jakość ponad ilość", "ps": ["Lepiej mieć 15 doskonałych zdjęć niż 100 podobnych. Odrzuć rozmyte i powtarzające się ujęcia."]},
   {"h2": "Pomyśl o przeznaczeniu", "ps": ["Inne kadry sprawdzą się na ścianę (pionowe portrety), inne do albumu czy na kartki dla rodziny."]},
   {"h2": "Dopasuj pakiet do potrzeb", "ps": ["Jeśli chcesz więcej wariantów, w BoboFoto.pl pakiet Premium daje 10 gotowych zdjęć w różnych stylizacjach."]},
 ],
},
]
